"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const backtrackingProblems: DsaProblem[] = [
  {
    id: "backtracking:subsets",
    topic: "backtracking",
    title: "All Subsets",
    difficulty: "medium",
    statement: "Return every subset of a list of distinct numbers. Build them in the standard backtracking order shown in the example.",
    examples: [{ input: "[1, 2]", output: "[[], [1], [1,2], [2]]" }],
    approachQuiz: { prompt: "Generate all subsets via…", options: ["Choose / explore / un-choose", "Sorting", "A single loop"], answer: "Choose / explore / un-choose", explain: "At each index, include it (recurse) then exclude it (backtrack)." },
    hints: ["Record the current path at every step.", "From a start index, try adding each later element.", "After recursing, remove it (un-choose) to try the next."],
    approach: "Backtracking: record the current path, then for each index from 'start' choose that element, recurse with start=i+1, and pop it to explore the rest.",
    pythonCode: ["def subsets(nums):", "    res = []", "    def bt(start, path):", "        res.append(path[:])", "        for i in range(start, len(nums)):", "            path.append(nums[i])", "            bt(i + 1, path)", "            path.pop()", "    bt(0, [])", "    return res"],
    complexity: { time: "O(2ⁿ)", space: "O(n)" },
    takeaway: "Subsets: choose → recurse → un-choose at each index.",
    code: { starter: "def subsets(nums):\n    # return all subsets\n    pass", functionName: "subsets", tests: [{ args: [[1, 2]], expected: [[], [1], [1, 2], [2]] }, { args: [[]], expected: [[]] }] },
  },
  {
    id: "backtracking:permutations",
    topic: "backtracking",
    title: "All Permutations",
    difficulty: "medium",
    statement: "Return every ordering of a list of distinct numbers (standard backtracking order).",
    examples: [{ input: "[1, 2]", output: "[[1,2], [2,1]]" }],
    approachQuiz: { prompt: "Build permutations by…", options: ["Picking each unused element in turn", "Sorting", "Two pointers"], answer: "Picking each unused element in turn", explain: "Track which are used; place each unused one, recurse, then free it." },
    hints: ["Track which elements are already used.", "When the path is full, record it.", "After recursing, mark the element unused again."],
    approach: "Backtracking with a 'used' flag per element: when the path length equals n, record it; otherwise try each unused element, recurse, then un-use it.",
    pythonCode: ["def permutations(nums):", "    res = []", "    def bt(path, used):", "        if len(path) == len(nums):", "            res.append(path[:]); return", "        for i in range(len(nums)):", "            if used[i]: continue", "            used[i] = True; path.append(nums[i])", "            bt(path, used)", "            path.pop(); used[i] = False", "    bt([], [False] * len(nums))", "    return res"],
    complexity: { time: "O(n·n!)", space: "O(n)" },
    takeaway: "Permutations: place each unused element, recurse, then free it.",
    code: { starter: "def permutations(nums):\n    # return all orderings\n    pass", functionName: "permutations", tests: [{ args: [[1, 2]], expected: [[1, 2], [2, 1]] }, { args: [[1]], expected: [[1]] }] },
  },
  {
    id: "backtracking:combinations",
    topic: "backtracking",
    title: "Combinations of k from n",
    difficulty: "medium",
    statement: "Return all ways to choose k numbers from 1..n (standard order).",
    examples: [{ input: "n = 4, k = 2", output: "[[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]]" }],
    approachQuiz: { prompt: "Avoid duplicate combinations by…", options: ["Only moving forward (start index)", "Sorting the output", "Using a set"], answer: "Only moving forward (start index)", explain: "Recursing from i+1 guarantees increasing, non-repeating picks." },
    hints: ["Pick numbers in increasing order to avoid repeats.", "Carry a 'start' value.", "When the path has k numbers, record it."],
    approach: "Backtracking from a start value: when the path reaches size k, record it; otherwise try each number from start to n, recurse from i+1, then pop.",
    pythonCode: ["def combine(n, k):", "    res = []", "    def bt(start, path):", "        if len(path) == k:", "            res.append(path[:]); return", "        for i in range(start, n + 1):", "            path.append(i)", "            bt(i + 1, path)", "            path.pop()", "    bt(1, [])", "    return res"],
    complexity: { time: "O(C(n,k)·k)", space: "O(k)" },
    takeaway: "Combinations: advance the start index so picks only increase.",
    code: { starter: "def combine(n, k):\n    # all k-combinations of 1..n\n    pass", functionName: "combine", tests: [{ args: [4, 2], expected: [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]] }, { args: [3, 3], expected: [[1, 2, 3]] }] },
  },
  {
    id: "backtracking:parentheses",
    topic: "backtracking",
    title: "Generate Valid Parentheses",
    difficulty: "hard",
    statement: "Return all valid strings of n pairs of parentheses (standard order).",
    examples: [{ input: "n = 2", output: '["(())", "()()"]' }],
    approachQuiz: { prompt: "Keep only valid strings by…", options: ["Constraining when you may add ( or )", "Generating all then filtering", "Sorting"], answer: "Constraining when you may add ( or )", explain: "Add '(' while open < n; add ')' only while close < open." },
    hints: ["Track how many '(' and ')' you've placed.", "You can add '(' while open < n.", "You can add ')' only if close < open."],
    approach: "Backtracking with counts: add '(' if open < n, add ')' if close < open. When the string reaches length 2n, record it.",
    pythonCode: ["def generate_parens(n):", "    res = []", "    def bt(s, open_, close):", "        if len(s) == 2 * n:", "            res.append(s); return", "        if open_ < n: bt(s + '(', open_ + 1, close)", "        if close < open_: bt(s + ')', open_, close + 1)", "    bt('', 0, 0)", "    return res"],
    complexity: { time: "O(Catalan(n))", space: "O(n)" },
    takeaway: "Prune invalid branches early with constraints (open/close counts).",
    code: { starter: "def generate_parens(n):\n    # all valid parenthesis strings of n pairs\n    pass", functionName: "generate_parens", tests: [{ args: [2], expected: ["(())", "()()"] }, { args: [1], expected: ["()"] }] },
  },
];
