"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const dynamicProgrammingProblems: DsaProblem[] = [
  {
    id: "dynamic-programming:climb-stairs",
    topic: "dynamic-programming",
    title: "Climbing Stairs",
    difficulty: "easy",
    statement: "You can climb 1 or 2 steps at a time. Return how many distinct ways there are to reach the top of n stairs.",
    examples: [{ input: "5", output: "8" }],
    approachQuiz: { prompt: "Ways(n) equals…", options: ["ways(n-1) + ways(n-2)", "n × ways(n-1)", "2 × ways(n-1)"], answer: "ways(n-1) + ways(n-2)", explain: "Your last move was a 1-step or a 2-step — it's Fibonacci." },
    hints: ["The last step was either 1 or 2 stairs.", "So ways(n) = ways(n-1) + ways(n-2).", "Keep the last two values instead of recursing."],
    approach: "Bottom-up DP (Fibonacci): base ways(1)=1, ways(2)=2; each next is the sum of the previous two. Keep two rolling variables.",
    pythonCode: ["def climb_stairs(n):", "    if n <= 2:", "        return n", "    a, b = 1, 2", "    for _ in range(3, n + 1):", "        a, b = b, a + b", "    return b"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Climbing stairs is Fibonacci — store the last two answers.",
    code: { starter: "def climb_stairs(n):\n    # number of ways to climb n stairs (1 or 2 at a time)\n    pass", functionName: "climb_stairs", tests: [{ args: [5], expected: 8 }, { args: [1], expected: 1 }, { args: [3], expected: 3 }] },
  },
  {
    id: "dynamic-programming:fib",
    topic: "dynamic-programming",
    title: "Fibonacci (Bottom-Up)",
    difficulty: "easy",
    statement: "Return the n-th Fibonacci number (fib(0)=0, fib(1)=1) WITHOUT exponential recursion.",
    examples: [{ input: "10", output: "55" }],
    approachQuiz: { prompt: "Make naive fib fast by…", options: ["Caching / building bottom-up", "Sorting", "Two pointers"], answer: "Caching / building bottom-up", explain: "Store sub-answers so each is computed once — O(n)." },
    hints: ["Naive recursion recomputes the same values.", "Build up from fib(0) and fib(1).", "Keep only the last two."],
    approach: "Iterate from 2 to n carrying the previous two Fibonacci numbers; return the last. This is memoisation made iterative.",
    pythonCode: ["def fib_dp(n):", "    if n < 2:", "        return n", "    a, b = 0, 1", "    for _ in range(2, n + 1):", "        a, b = b, a + b", "    return b"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "DP turns exponential recursion into O(n) by reusing sub-answers.",
    code: { starter: "def fib_dp(n):\n    # nth Fibonacci, bottom-up\n    pass", functionName: "fib_dp", tests: [{ args: [10], expected: 55 }, { args: [0], expected: 0 }, { args: [1], expected: 1 }] },
  },
  {
    id: "dynamic-programming:coin-change",
    topic: "dynamic-programming",
    title: "Coin Change (Min Coins)",
    difficulty: "medium",
    statement: "Given coin denominations and an amount, return the FEWEST coins that make the amount, or -1 if impossible. (Greedy can be wrong here — use DP.)",
    examples: [{ input: "[1,3,4], amount = 6", output: "2", note: "3 + 3" }],
    approachQuiz: { prompt: "Why DP, not greedy?", options: ["Greedy can miss the optimum (e.g. 6 from [1,3,4])", "DP is always faster", "Greedy can't handle coins"], answer: "Greedy can miss the optimum (e.g. 6 from [1,3,4])", explain: "Greedy gives 4+1+1=3; DP finds 3+3=2." },
    hints: ["dp[a] = fewest coins to make amount a.", "Try each coin c ≤ a: dp[a] = min(dp[a], dp[a-c] + 1).", "Build dp from 0 up to the target."],
    approach: "Bottom-up table dp where dp[a] is the min coins for amount a. For each amount, try every coin ≤ a and take 1 + dp[a-c]. Unreachable stays 'infinity' → return -1.",
    pythonCode: ["def coin_change(coins, amount):", "    INF = amount + 1", "    dp = [0] + [INF] * amount", "    for a in range(1, amount + 1):", "        for c in coins:", "            if c <= a:", "                dp[a] = min(dp[a], dp[a - c] + 1)", "    return dp[amount] if dp[amount] != INF else -1"],
    complexity: { time: "O(amount × coins)", space: "O(amount)" },
    takeaway: "Coin change needs DP — greedy can miss the true minimum.",
    code: { starter: "def coin_change(coins, amount):\n    # fewest coins for amount, or -1\n    pass", functionName: "coin_change", tests: [{ args: [[1, 3, 4], 6], expected: 2 }, { args: [[2], 3], expected: -1 }, { args: [[1], 0], expected: 0 }] },
  },
  {
    id: "dynamic-programming:max-subarray",
    topic: "dynamic-programming",
    title: "Maximum Subarray (Kadane)",
    difficulty: "medium",
    statement: "Return the largest sum of any contiguous subarray.",
    examples: [{ input: "[-2,1,-3,4,-1,2,1,-5,4]", output: "6", note: "[4,-1,2,1]" }],
    approachQuiz: { prompt: "Kadane's key decision at each element?", options: ["Extend the run, or start fresh here", "Sort first", "Two pointers"], answer: "Extend the run, or start fresh here", explain: "cur = max(x, cur + x): drop the past if it's dragging you down." },
    hints: ["Track the best subarray sum ENDING at the current element.", "Either extend the previous run or restart at x.", "Keep the overall best."],
    approach: "Kadane's DP: cur = max(x, cur + x) decides whether to extend or restart; best tracks the maximum cur seen.",
    pythonCode: ["def max_subarray(nums):", "    best = cur = nums[0]", "    for x in nums[1:]:", "        cur = max(x, cur + x)", "        best = max(best, cur)", "    return best"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Kadane: extend the run or restart; keep the running best.",
    code: { starter: "def max_subarray(nums):\n    # largest contiguous subarray sum\n    pass", functionName: "max_subarray", tests: [{ args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 }, { args: [[1]], expected: 1 }, { args: [[-3, -1, -2]], expected: -1 }] },
  },
  {
    id: "dynamic-programming:lcs",
    topic: "dynamic-programming",
    title: "Longest Common Subsequence",
    difficulty: "hard",
    statement: "Return the length of the longest subsequence common to two strings (characters in order, not necessarily contiguous).",
    examples: [{ input: '"abcde", "ace"', output: "3" }],
    approachQuiz: { prompt: "LCS recurrence when chars match?", options: ["1 + LCS of both remainders", "max of the two remainders", "0"], answer: "1 + LCS of both remainders", explain: "Matching chars extend the subsequence; otherwise take the better of dropping one char." },
    hints: ["Compare characters position by position.", "Match → 1 + diagonal. No match → best of left/up.", "Use a 2-D table dp[i][j]."],
    approach: "2-D DP: dp[i][j] = LCS of a[:i], b[:j]. If a[i-1]==b[j-1], dp[i][j]=dp[i-1][j-1]+1; else max(dp[i-1][j], dp[i][j-1]).",
    pythonCode: ["def lcs(a, b):", "    m, n = len(a), len(b)", "    dp = [[0] * (n + 1) for _ in range(m + 1)]", "    for i in range(1, m + 1):", "        for j in range(1, n + 1):", "            if a[i-1] == b[j-1]:", "                dp[i][j] = dp[i-1][j-1] + 1", "            else:", "                dp[i][j] = max(dp[i-1][j], dp[i][j-1])", "    return dp[m][n]"],
    complexity: { time: "O(m·n)", space: "O(m·n)" },
    takeaway: "LCS: 2-D table; match extends the diagonal, else take the best neighbour.",
    code: { starter: "def lcs(a, b):\n    # length of the longest common subsequence\n    pass", functionName: "lcs", tests: [{ args: ["abcde", "ace"], expected: 3 }, { args: ["abc", "abc"], expected: 3 }, { args: ["abc", "def"], expected: 0 }] },
  },
];
