"use client";

import type { DsaProblem } from "@/lib/dsa/types";

// Graphs are given as an adjacency list: adj[i] = list of i's neighbours.
const ADJ6 = [[1, 2], [0, 3], [0, 3], [1, 2, 4], [3, 5], [4]];
const ADJ2 = [[1], [0], [3], [2]];

export const graphsProblems: DsaProblem[] = [
  {
    id: "graphs:bfs",
    topic: "graphs",
    title: "BFS Order",
    difficulty: "medium",
    statement: "Return the breadth-first order from a start node. adj[i] lists node i's neighbours.",
    examples: [{ input: "ADJ6, start = 0", output: "[0, 1, 2, 3, 4, 5]" }],
    approachQuiz: { prompt: "BFS uses a…", options: ["Queue", "Stack", "Heap"], answer: "Queue", explain: "A FIFO queue visits nodes ring by ring (nearest first)." },
    hints: ["Track visited nodes to avoid loops.", "Use a queue: dequeue a node, enqueue unseen neighbours.", "Record each node when you dequeue it."],
    approach: "Start a queue and a 'seen' set with the start node. Dequeue, record, and enqueue each unseen neighbour, marking it seen.",
    pythonCode: ["def bfs_order(adj, start):", "    from collections import deque", "    seen = {start}; q = deque([start]); out = []", "    while q:", "        node = q.popleft(); out.append(node)", "        for nb in adj[node]:", "            if nb not in seen:", "                seen.add(nb); q.append(nb)", "    return out"],
    complexity: { time: "O(V + E)", space: "O(V)" },
    takeaway: "BFS = queue + seen set; visits nearest nodes first.",
    code: { starter: "def bfs_order(adj, start):\n    # breadth-first visit order\n    pass", functionName: "bfs_order", tests: [{ args: [ADJ6, 0], expected: [0, 1, 2, 3, 4, 5] }, { args: [[[1], [0]], 1], expected: [1, 0] }] },
  },
  {
    id: "graphs:dfs",
    topic: "graphs",
    title: "DFS Order",
    difficulty: "medium",
    statement: "Return the depth-first order from a start node (recurse into the first unseen neighbour each time).",
    examples: [{ input: "ADJ6, start = 0", output: "[0, 1, 3, 2, 4, 5]" }],
    approachQuiz: { prompt: "DFS uses a…", options: ["Stack / recursion", "Queue", "Heap"], answer: "Stack / recursion", explain: "Go as deep as possible, then backtrack — that's a stack." },
    hints: ["Visit a node, then dive into its neighbours.", "Mark nodes seen to avoid loops.", "Recursion is the natural fit."],
    approach: "Mark the node seen and record it, then recurse into each unseen neighbour in order.",
    pythonCode: ["def dfs_order(adj, start):", "    seen = set(); out = []", "    def go(n):", "        seen.add(n); out.append(n)", "        for nb in adj[n]:", "            if nb not in seen: go(nb)", "    go(start)", "    return out"],
    complexity: { time: "O(V + E)", space: "O(V)" },
    takeaway: "DFS = recursion/stack; goes deep before wide.",
    code: { starter: "def dfs_order(adj, start):\n    # depth-first visit order\n    pass", functionName: "dfs_order", tests: [{ args: [ADJ6, 0], expected: [0, 1, 3, 2, 4, 5] }, { args: [[[1], [0]], 0], expected: [0, 1] }] },
  },
  {
    id: "graphs:components",
    topic: "graphs",
    title: "Count Connected Components",
    difficulty: "medium",
    statement: "Count the connected components in an undirected graph (groups of nodes reachable from each other).",
    examples: [{ input: "ADJ2 (two pairs)", output: "2" }],
    approachQuiz: { prompt: "Count components by…", options: ["DFS/BFS from each unvisited node", "Counting edges", "Sorting nodes"], answer: "DFS/BFS from each unvisited node", explain: "Each new traversal you start is one more component." },
    hints: ["Start a traversal from any unvisited node.", "That traversal marks one whole component.", "Count how many traversals you need."],
    approach: "Loop over all nodes; whenever you hit an unvisited one, run DFS/BFS to mark its whole component and add 1 to the count.",
    pythonCode: ["def count_components(adj):", "    seen = set(); count = 0", "    def go(n):", "        seen.add(n)", "        for nb in adj[n]:", "            if nb not in seen: go(nb)", "    for i in range(len(adj)):", "        if i not in seen:", "            count += 1; go(i)", "    return count"],
    complexity: { time: "O(V + E)", space: "O(V)" },
    takeaway: "Each fresh DFS/BFS from an unvisited node = one component.",
    code: { starter: "def count_components(adj):\n    # number of connected components\n    pass", functionName: "count_components", tests: [{ args: [ADJ2], expected: 2 }, { args: [ADJ6], expected: 1 }, { args: [[[], [], []]], expected: 3 }] },
  },
  {
    id: "graphs:has-path",
    topic: "graphs",
    title: "Does a Path Exist?",
    difficulty: "easy",
    statement: "Return True if there is a path from src to dst.",
    examples: [{ input: "ADJ6, 0 → 5", output: "true" }],
    approachQuiz: { prompt: "Check reachability with…", options: ["DFS or BFS", "Sorting", "Binary search"], answer: "DFS or BFS", explain: "Explore from src; if you ever reach dst, a path exists." },
    hints: ["Explore outward from src.", "Mark visited to avoid cycles.", "If you reach dst, return True."],
    approach: "Run DFS/BFS from src; if you ever reach dst return True. If the search finishes without reaching it, return False.",
    pythonCode: ["def has_path(adj, src, dst):", "    seen = set(); stack = [src]", "    while stack:", "        n = stack.pop()", "        if n == dst: return True", "        if n in seen: continue", "        seen.add(n)", "        for nb in adj[n]:", "            if nb not in seen: stack.append(nb)", "    return False"],
    complexity: { time: "O(V + E)", space: "O(V)" },
    takeaway: "Reachability = DFS/BFS from src looking for dst.",
    code: { starter: "def has_path(adj, src, dst):\n    # True if dst is reachable from src\n    pass", functionName: "has_path", tests: [{ args: [ADJ6, 0, 5], expected: true }, { args: [ADJ2, 0, 3], expected: false }, { args: [ADJ6, 2, 2], expected: true }] },
  },
  {
    id: "graphs:shortest-path",
    topic: "graphs",
    title: "Shortest Path Length",
    difficulty: "medium",
    statement: "Return the fewest edges between src and dst (unweighted). Return -1 if unreachable, 0 if src == dst.",
    examples: [{ input: "ADJ6, 0 → 5", output: "4" }],
    approachQuiz: { prompt: "Fewest edges (unweighted) via…", options: ["BFS", "DFS", "Sorting"], answer: "BFS", explain: "BFS reaches every node by the minimum number of edges." },
    hints: ["BFS expands ring by ring.", "Track the distance with each queued node.", "The first time you reach dst is the shortest."],
    approach: "BFS from src tracking distance; the first time you reach dst, return its distance. If BFS finishes, return -1.",
    pythonCode: ["def shortest_path_len(adj, src, dst):", "    from collections import deque", "    if src == dst: return 0", "    seen = {src}; q = deque([(src, 0)])", "    while q:", "        n, d = q.popleft()", "        for nb in adj[n]:", "            if nb == dst: return d + 1", "            if nb not in seen:", "                seen.add(nb); q.append((nb, d + 1))", "    return -1"],
    complexity: { time: "O(V + E)", space: "O(V)" },
    takeaway: "Unweighted shortest path = BFS distance (first arrival wins).",
    code: { starter: "def shortest_path_len(adj, src, dst):\n    # fewest edges src->dst, or -1\n    pass", functionName: "shortest_path_len", tests: [{ args: [ADJ6, 0, 5], expected: 4 }, { args: [ADJ6, 0, 0], expected: 0 }, { args: [ADJ2, 0, 3], expected: -1 }] },
  },
];
