"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const greedyProblems: DsaProblem[] = [
  {
    id: "greedy:coin-change",
    topic: "greedy",
    title: "Fewest Coins (Greedy)",
    difficulty: "easy",
    statement: "Given canonical coin denominations and an amount, return the fewest coins needed using the greedy method (always take the biggest coin that fits).",
    examples: [{ input: "[25,10,5,1], amount = 63", output: "6" }],
    approachQuiz: { prompt: "Greedy coin change works by…", options: ["Taking the largest coin that fits, repeatedly", "Trying all combinations", "Sorting the amount"], answer: "Taking the largest coin that fits, repeatedly", explain: "For canonical systems the biggest-first choice is optimal." },
    hints: ["Sort coins from biggest to smallest.", "Take as many of the biggest as fit.", "Move to the next coin with the remainder."],
    approach: "Sort denominations descending. For each, take as many as fit (subtracting from the amount) and count them.",
    pythonCode: ["def min_coins(coins, amount):", "    coins = sorted(coins, reverse=True)", "    count = 0", "    for c in coins:", "        while c <= amount:", "            amount -= c", "            count += 1", "    return count"],
    complexity: { time: "O(n + amount/coin)", space: "O(1)" },
    takeaway: "Greedy coin change: biggest coin first (works for canonical sets).",
    code: { starter: "def min_coins(coins, amount):\n    # fewest coins for amount (greedy)\n    pass", functionName: "min_coins", tests: [{ args: [[25, 10, 5, 1], 63], expected: 6 }, { args: [[1], 5], expected: 5 }, { args: [[5, 1], 0], expected: 0 }] },
  },
  {
    id: "greedy:activity-selection",
    topic: "greedy",
    title: "Max Non-Overlapping Activities",
    difficulty: "medium",
    statement: "Given intervals [start, end], return the most activities you can attend without overlaps.",
    examples: [{ input: "[[1,2],[2,3],[3,4],[1,3]]", output: "3" }],
    approachQuiz: { prompt: "Greedy choice for activity selection?", options: ["Always take the one that ends earliest", "Take the longest", "Take the earliest start"], answer: "Always take the one that ends earliest", explain: "Finishing early leaves the most room for the rest." },
    hints: ["Sort by END time.", "Greedily take an activity if it starts after the last one ended.", "Earliest finish frees up the most time."],
    approach: "Sort intervals by end time. Walk through, taking each interval whose start is ≥ the last taken end; update the end each time.",
    pythonCode: ["def max_activities(intervals):", "    intervals = sorted(intervals, key=lambda x: x[1])", "    count = 0", "    end = float('-inf')", "    for s, e in intervals:", "        if s >= end:", "            count += 1", "            end = e", "    return count"],
    complexity: { time: "O(n log n)", space: "O(1)" },
    takeaway: "Activity selection: sort by end time, take earliest-finishing first.",
    code: { starter: "def max_activities(intervals):\n    # max non-overlapping intervals\n    pass", functionName: "max_activities", tests: [{ args: [[[1, 2], [2, 3], [3, 4], [1, 3]]], expected: 3 }, { args: [[[1, 5]]], expected: 1 }, { args: [[[1, 3], [2, 4], [3, 5]]], expected: 2 }] },
  },
  {
    id: "greedy:jump-game",
    topic: "greedy",
    title: "Can You Reach the End?",
    difficulty: "medium",
    statement: "Each number is the max jump length from that index. Return True if you can reach the last index from the first.",
    examples: [{ input: "[2,3,1,1,4]", output: "true" }, { input: "[3,2,1,0,4]", output: "false" }],
    approachQuiz: { prompt: "Greedy jump game tracks…", options: ["The furthest index reachable so far", "Every path", "The sum"], answer: "The furthest index reachable so far", explain: "If your position ever exceeds the furthest reach, you're stuck." },
    hints: ["Track the furthest index you can reach.", "If your current index passes that reach, fail.", "Otherwise extend the reach with i + nums[i]."],
    approach: "Sweep left to right keeping the furthest reachable index. If an index is beyond the current reach, return False; otherwise extend the reach.",
    pythonCode: ["def can_jump(nums):", "    reach = 0", "    for i, x in enumerate(nums):", "        if i > reach:", "            return False", "        reach = max(reach, i + x)", "    return True"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Jump game: greedily track the furthest reachable index.",
    code: { starter: "def can_jump(nums):\n    # True if the last index is reachable\n    pass", functionName: "can_jump", tests: [{ args: [[2, 3, 1, 1, 4]], expected: true }, { args: [[3, 2, 1, 0, 4]], expected: false }, { args: [[0]], expected: true }] },
  },
  {
    id: "greedy:max-profit",
    topic: "greedy",
    title: "Best Time to Buy & Sell",
    difficulty: "easy",
    statement: "Given daily prices, return the max profit from one buy and one later sell (0 if no profit is possible).",
    examples: [{ input: "[7,1,5,3,6,4]", output: "5", note: "buy 1, sell 6" }],
    approachQuiz: { prompt: "One-pass profit by tracking…", options: ["The minimum price so far", "The maximum price", "The average"], answer: "The minimum price so far", explain: "Best sell today = today's price − cheapest day before it." },
    hints: ["You must buy before you sell.", "Track the lowest price seen so far.", "Best profit = current price − lowest-so-far."],
    approach: "Walk the prices tracking the minimum so far; at each day compute price − min and keep the best.",
    pythonCode: ["def max_profit(prices):", "    min_p = prices[0]", "    best = 0", "    for p in prices:", "        min_p = min(min_p, p)", "        best = max(best, p - min_p)", "    return best"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Buy-sell: track the cheapest day so far, maximise today − that.",
    code: { starter: "def max_profit(prices):\n    # max profit from one buy then one sell\n    pass", functionName: "max_profit", tests: [{ args: [[7, 1, 5, 3, 6, 4]], expected: 5 }, { args: [[7, 6, 4, 3, 1]], expected: 0 }, { args: [[1, 2]], expected: 1 }] },
  },
];
