"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const hashMapsProblems: DsaProblem[] = [
  {
    id: "hash-maps:two-sum",
    topic: "hash-maps",
    title: "Two Sum",
    difficulty: "easy",
    statement: "Given a list of numbers and a target, return the indices of the two numbers that add up to the target. Exactly one answer exists.",
    examples: [{ input: "[2, 7, 11, 15], target = 9", output: "[0, 1]" }],
    approachQuiz: { prompt: "Beat the O(n²) double loop?", options: ["A hash map of seen values", "Sort then two pointers", "Binary search"], answer: "A hash map of seen values", explain: "Store each value's index; for each x, check if target - x was already seen — O(n)." },
    hints: ["For each number, what 'partner' do you need?", "You need target - x.", "Remember each value's index in a hash map as you go."],
    approach: "Walk once, keeping a map of value → index. For each x, if target - x is already in the map you've found the pair; otherwise record x.",
    pythonCode: ["def two_sum(arr, target):", "    seen = {}", "    for i, x in enumerate(arr):", "        if target - x in seen:", "            return [seen[target - x], i]", "        seen[x] = i", "    return []"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Hash map of seen values turns pair-finding from O(n²) into O(n).",
    code: { starter: "def two_sum(arr, target):\n    # return indices of the two numbers adding to target\n    pass", functionName: "two_sum", tests: [{ args: [[2, 7, 11, 15], 9], expected: [0, 1] }, { args: [[3, 2, 4], 6], expected: [1, 2] }, { args: [[3, 3], 6], expected: [0, 1] }] },
  },
  {
    id: "hash-maps:contains-duplicate",
    topic: "hash-maps",
    title: "Contains Duplicate",
    difficulty: "easy",
    statement: "Return True if any value appears at least twice in the list, else False.",
    examples: [{ input: "[1, 2, 3, 1]", output: "true" }, { input: "[1, 2, 3]", output: "false" }],
    approachQuiz: { prompt: "Detect duplicates fastest?", options: ["A set", "Sort and scan", "Nested loops"], answer: "A set", explain: "A set gives O(1) membership — add as you go, or compare set size to length." },
    hints: ["A set stores only unique values.", "If the set is smaller than the list…", "…there was a duplicate."],
    approach: "Build a set; if its size differs from the list length there was a duplicate. (Or return early the first time you re-see a value.)",
    pythonCode: ["def has_dup(arr):", "    return len(set(arr)) != len(arr)"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "A set gives O(1) membership — perfect for duplicate detection.",
    code: { starter: "def has_dup(arr):\n    # True if any value repeats\n    pass", functionName: "has_dup", tests: [{ args: [[1, 2, 3, 1]], expected: true }, { args: [[1, 2, 3]], expected: false }, { args: [[]], expected: false }] },
  },
  {
    id: "hash-maps:first-unique",
    topic: "hash-maps",
    title: "First Unique Character",
    difficulty: "medium",
    statement: "Return the index of the first character that appears exactly once, or -1 if there is none.",
    examples: [{ input: '"leetcode"', output: "0" }, { input: '"aabb"', output: "-1" }],
    approachQuiz: { prompt: "Find the first non-repeating char?", options: ["Count frequencies, then scan", "Sort the string", "Two pointers"], answer: "Count frequencies, then scan", explain: "Count each char once (hash map), then scan for the first with count 1." },
    hints: ["First, how many times does each character appear?", "A frequency map answers that in one pass.", "Then scan left to right for the first count of 1."],
    approach: "Build a frequency map of all characters. Then scan the string and return the first index whose character has a count of 1.",
    pythonCode: ["def first_uniq(s):", "    from collections import Counter", "    c = Counter(s)", "    for i, ch in enumerate(s):", "        if c[ch] == 1:", "            return i", "    return -1"],
    complexity: { time: "O(n)", space: "O(1) (fixed alphabet)" },
    takeaway: "Two passes with a frequency map: count, then find the first unique.",
    code: { starter: "def first_uniq(s):\n    # index of the first non-repeating char, or -1\n    pass", functionName: "first_uniq", tests: [{ args: ["leetcode"], expected: 0 }, { args: ["loveleetcode"], expected: 2 }, { args: ["aabb"], expected: -1 }] },
  },
  {
    id: "hash-maps:majority",
    topic: "hash-maps",
    title: "Majority Element",
    difficulty: "medium",
    statement: "Return the element that appears more than ⌊n/2⌋ times. One always exists.",
    examples: [{ input: "[2, 2, 1, 1, 1, 2, 2]", output: "2" }],
    approachQuiz: { prompt: "Find the >n/2 element?", options: ["Count with a hash map", "Sort and take the middle", "Both work"], answer: "Both work", explain: "Counting is O(n) time/space; sorting puts the majority at the middle. (Boyer-Moore does O(1) space.)" },
    hints: ["Count how many times each value appears.", "The answer's count exceeds n/2.", "Return it as soon as its count passes the threshold."],
    approach: "Tally counts in a hash map; return the value whose count first exceeds n/2. (Boyer-Moore voting can do it in O(1) space.)",
    pythonCode: ["def majority(arr):", "    counts = {}", "    for x in arr:", "        counts[x] = counts.get(x, 0) + 1", "        if counts[x] > len(arr) // 2:", "            return x", "    return -1"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Frequency counting finds a majority; Boyer-Moore does it in O(1) space.",
    code: { starter: "def majority(arr):\n    # element appearing more than n/2 times\n    pass", functionName: "majority", tests: [{ args: [[3, 2, 3]], expected: 3 }, { args: [[2, 2, 1, 1, 1, 2, 2]], expected: 2 }, { args: [[1]], expected: 1 }] },
  },
  {
    id: "hash-maps:intersection",
    topic: "hash-maps",
    title: "Intersection of Two Lists",
    difficulty: "easy",
    statement: "Return the unique values present in BOTH lists, sorted ascending.",
    examples: [{ input: "[1, 2, 2, 1], [2, 2]", output: "[2]" }],
    approachQuiz: { prompt: "Find common elements fast?", options: ["Put one in a set, check the other", "Nested loops", "Sort both fully"], answer: "Put one in a set, check the other", explain: "Set membership is O(1); intersect, then sort the unique result." },
    hints: ["Sets make membership checks instant.", "Put one list in a set.", "Keep values from the other that are in it (unique)."],
    approach: "Convert both to sets and intersect them, then sort the result for a deterministic order.",
    pythonCode: ["def intersection(a, b):", "    return sorted(set(a) & set(b))"],
    complexity: { time: "O(n + m)", space: "O(n)" },
    takeaway: "Set intersection finds common elements in linear time.",
    code: { starter: "def intersection(a, b):\n    # sorted unique values in both lists\n    pass", functionName: "intersection", tests: [{ args: [[1, 2, 2, 1], [2, 2]], expected: [2] }, { args: [[4, 9, 5], [9, 4, 9, 8, 4]], expected: [4, 9] }, { args: [[1], [2]], expected: [] }] },
  },
];
