"use client";

import type { DsaProblem } from "@/lib/dsa/types";

// Heaps are given as a Python list (array form): children of i are 2i+1, 2i+2.

export const heapsProblems: DsaProblem[] = [
  {
    id: "heaps:push",
    topic: "heaps",
    title: "Push onto a Max-Heap",
    difficulty: "medium",
    statement: "Given a valid max-heap (as an array) and a value, push the value and bubble it up. Return the new heap array.",
    examples: [{ input: "[9, 5, 7], val = 10", output: "[10, 9, 7, 5]" }],
    approachQuiz: { prompt: "After appending, restore the heap by…", options: ["Bubbling up (swap with parent while bigger)", "Sorting the whole array", "Bubbling down"], answer: "Bubbling up (swap with parent while bigger)", explain: "A pushed value only violates order upward, so sift it up." },
    hints: ["Append the value at the end.", "Its parent is at index (i-1)//2.", "Swap up while it's bigger than its parent."],
    approach: "Append the value. Set i to the last index; while i > 0 and heap[i] > heap[parent], swap and move up.",
    pythonCode: ["def heap_push(heap, val):", "    heap = heap[:]", "    heap.append(val)", "    i = len(heap) - 1", "    while i > 0:", "        p = (i - 1) // 2", "        if heap[i] <= heap[p]: break", "        heap[i], heap[p] = heap[p], heap[i]", "        i = p", "    return heap"],
    complexity: { time: "O(log n)", space: "O(n)" },
    takeaway: "Push = append then bubble up (swap with parent while bigger).",
    code: { starter: "def heap_push(heap, val):\n    # push val into the max-heap; return new heap\n    pass", functionName: "heap_push", tests: [{ args: [[9, 5, 7], 10], expected: [10, 9, 7, 5] }, { args: [[], 1], expected: [1] }, { args: [[5], 3], expected: [5, 3] }] },
  },
  {
    id: "heaps:is-max-heap",
    topic: "heaps",
    title: "Is It a Max-Heap?",
    difficulty: "medium",
    statement: "Return True if an array satisfies the max-heap property (every parent ≥ its children).",
    examples: [{ input: "[10, 9, 7, 5]", output: "true" }, { input: "[1, 2, 3]", output: "false" }],
    approachQuiz: { prompt: "Children of index i are at…", options: ["2i+1 and 2i+2", "i-1 and i+1", "i/2"], answer: "2i+1 and 2i+2", explain: "Array heaps map parent i to children 2i+1, 2i+2." },
    hints: ["Each parent must be ≥ both children.", "Children of i are 2i+1 and 2i+2.", "Check every index that has children."],
    approach: "For each index, verify it's ≥ each existing child (2i+1, 2i+2). If any check fails, it's not a max-heap.",
    pythonCode: ["def is_max_heap(arr):", "    n = len(arr)", "    for i in range(n):", "        l, r = 2*i + 1, 2*i + 2", "        if l < n and arr[l] > arr[i]: return False", "        if r < n and arr[r] > arr[i]: return False", "    return True"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Heap index math: children of i are 2i+1 and 2i+2.",
    code: { starter: "def is_max_heap(arr):\n    # True if arr is a valid max-heap\n    pass", functionName: "is_max_heap", tests: [{ args: [[10, 9, 7, 5]], expected: true }, { args: [[1, 2, 3]], expected: false }, { args: [[5]], expected: true }] },
  },
  {
    id: "heaps:kth-largest",
    topic: "heaps",
    title: "Kth Largest Element",
    difficulty: "medium",
    statement: "Return the k-th largest value in a list (k is 1-indexed).",
    examples: [{ input: "[3, 2, 1, 5, 6, 4], k = 2", output: "5" }],
    approachQuiz: { prompt: "Find the k-th largest?", options: ["A size-k min-heap (or sort)", "Two pointers", "Binary search the list"], answer: "A size-k min-heap (or sort)", explain: "A min-heap of size k keeps the k biggest; its root is the answer. Sorting also works." },
    hints: ["The k-th largest is at index k-1 after sorting descending.", "A heap of size k is the optimal tool.", "For now, sorting is clear and correct."],
    approach: "Sort descending and take index k-1. (Optimal: keep a min-heap of size k, O(n log k).)",
    pythonCode: ["def kth_largest(arr, k):", "    return sorted(arr, reverse=True)[k - 1]"],
    complexity: { time: "O(n log n), O(n log k) with a heap", space: "O(n)" },
    takeaway: "Top-K problems → a size-k heap (root is the k-th largest).",
    code: { starter: "def kth_largest(arr, k):\n    # the k-th largest (1-indexed)\n    pass", functionName: "kth_largest", tests: [{ args: [[3, 2, 1, 5, 6, 4], 2], expected: 5 }, { args: [[1], 1], expected: 1 }, { args: [[7, 7, 7], 2], expected: 7 }] },
  },
  {
    id: "heaps:top-k",
    topic: "heaps",
    title: "Top K Largest",
    difficulty: "medium",
    statement: "Return the k largest values, sorted from largest to smallest.",
    examples: [{ input: "[3, 1, 5, 2, 4], k = 3", output: "[5, 4, 3]" }],
    approachQuiz: { prompt: "Get the k biggest efficiently?", options: ["A size-k min-heap", "Bubble sort", "Two pointers"], answer: "A size-k min-heap", explain: "Keep the k biggest seen; evict the smallest when something bigger arrives." },
    hints: ["You only need the top k, not a full sort.", "A min-heap of size k holds the current top k.", "Sorting then slicing also works."],
    approach: "Sort descending and take the first k. (Optimal: a size-k min-heap in O(n log k).)",
    pythonCode: ["def top_k(arr, k):", "    return sorted(arr, reverse=True)[:k]"],
    complexity: { time: "O(n log n), O(n log k) with a heap", space: "O(n)" },
    takeaway: "Top-K: maintain a size-k heap instead of fully sorting.",
    code: { starter: "def top_k(arr, k):\n    # k largest values, largest first\n    pass", functionName: "top_k", tests: [{ args: [[3, 1, 5, 2, 4], 3], expected: [5, 4, 3] }, { args: [[1, 2], 1], expected: [2] }] },
  },
  {
    id: "heaps:kth-smallest",
    topic: "heaps",
    title: "Kth Smallest Element",
    difficulty: "easy",
    statement: "Return the k-th smallest value in a list (k is 1-indexed).",
    examples: [{ input: "[7, 3, 1, 5], k = 2", output: "3" }],
    approachQuiz: { prompt: "Mirror of k-th largest?", options: ["Size-k max-heap (or sort ascending)", "Queue", "Two pointers"], answer: "Size-k max-heap (or sort ascending)", explain: "A max-heap of size k keeps the k smallest; its root is the answer." },
    hints: ["After sorting ascending, the k-th smallest is at index k-1.", "A max-heap of size k is the optimal tool.", "Sorting is fine for now."],
    approach: "Sort ascending and take index k-1. (Optimal: a max-heap of size k.)",
    pythonCode: ["def kth_smallest(arr, k):", "    return sorted(arr)[k - 1]"],
    complexity: { time: "O(n log n)", space: "O(n)" },
    takeaway: "k-th smallest mirrors k-th largest — swap min/max heap roles.",
    code: { starter: "def kth_smallest(arr, k):\n    # the k-th smallest (1-indexed)\n    pass", functionName: "kth_smallest", tests: [{ args: [[7, 3, 1, 5], 2], expected: 3 }, { args: [[1], 1], expected: 1 }] },
  },
];
