"use client";

import type { DsaProblem } from "@/lib/dsa/types";

// Linked lists are given to the runnable function as a Python list of values,
// so they execute in the browser; the lesson visualizer shows real pointers.

export const linkedListsProblems: DsaProblem[] = [
  {
    id: "linked-lists:reverse",
    topic: "linked-lists",
    title: "Reverse a Linked List",
    difficulty: "easy",
    statement: "A linked list is given as a Python list of its values. Return its values reversed.",
    examples: [{ input: "[1, 2, 3]", output: "[3, 2, 1]" }],
    approachQuiz: { prompt: "Reverse a singly linked list by…", options: ["Flipping each next pointer", "Sorting it", "Using a hash map"], answer: "Flipping each next pointer", explain: "Walk the list once, repointing each node's next to the previous node." },
    hints: ["Keep a 'previous' pointer, starting at None.", "For each node, remember its next, then point it back at previous.", "Move previous and current forward."],
    approach: "With real nodes: keep prev=None and curr=head; each step save nxt=curr.next, set curr.next=prev, then prev=curr, curr=nxt. (As a list, that's just a reverse.)",
    pythonCode: ["def reverse_ll(vals):", "    # real pointers: prev=None; curr=head; flip each .next", "    return vals[::-1]"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Reverse a list by flipping each next pointer (prev/curr walk).",
    code: { starter: "def reverse_ll(vals):\n    # return the values reversed\n    pass", functionName: "reverse_ll", tests: [{ args: [[1, 2, 3]], expected: [3, 2, 1] }, { args: [[1]], expected: [1] }, { args: [[]], expected: [] }] },
  },
  {
    id: "linked-lists:middle",
    topic: "linked-lists",
    title: "Middle of the List",
    difficulty: "medium",
    statement: "Return the value of the middle node. If there are two middles, return the second. (List of values.)",
    examples: [{ input: "[1, 2, 3, 4, 5]", output: "3" }, { input: "[1, 2, 3, 4]", output: "3" }],
    approachQuiz: { prompt: "Find the middle in ONE pass?", options: ["Slow + fast pointers", "Count then re-walk", "Sort"], answer: "Slow + fast pointers", explain: "Fast moves twice as fast; when it reaches the end, slow is at the middle." },
    hints: ["Use two pointers at different speeds.", "Fast moves 2 steps, slow moves 1.", "When fast hits the end, slow is at the middle."],
    approach: "Slow/fast pointers: advance slow by 1 and fast by 2 each step. When fast runs off the end, slow sits on the middle node.",
    pythonCode: ["def middle(vals):", "    slow = fast = 0", "    while fast < len(vals) and fast + 1 < len(vals):", "        slow += 1", "        fast += 2", "    return vals[slow]"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Slow/fast pointers find the middle in a single pass.",
    code: { starter: "def middle(vals):\n    # return the middle value (second of two)\n    pass", functionName: "middle", tests: [{ args: [[1, 2, 3, 4, 5]], expected: 3 }, { args: [[1, 2, 3, 4]], expected: 3 }, { args: [[1]], expected: 1 }] },
  },
  {
    id: "linked-lists:remove-nth",
    topic: "linked-lists",
    title: "Remove Nth Node From End",
    difficulty: "medium",
    statement: "Remove the n-th node counting from the END and return the remaining values. (List of values.)",
    examples: [{ input: "[1, 2, 3, 4, 5], n = 2", output: "[1, 2, 3, 5]" }],
    approachQuiz: { prompt: "Find the nth-from-end in one pass?", options: ["Two pointers a gap of n apart", "Reverse then remove", "Count length twice"], answer: "Two pointers a gap of n apart", explain: "Advance a lead pointer n ahead; move both until lead hits the end — trail is at the node before the target." },
    hints: ["nth from the end = (length - n) from the start.", "A gap of n between two pointers reveals it in one pass.", "Remove that index and return the rest."],
    approach: "Two-pointer gap: move a fast pointer n steps ahead, then move both until fast reaches the end; slow lands just before the target. (As a list: index = len - n.)",
    pythonCode: ["def remove_nth(vals, n):", "    idx = len(vals) - n", "    return vals[:idx] + vals[idx+1:]"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "nth-from-end: a two-pointer gap of n finds it in one pass.",
    code: { starter: "def remove_nth(vals, n):\n    # remove the nth node from the end; return the rest\n    pass", functionName: "remove_nth", tests: [{ args: [[1, 2, 3, 4, 5], 2], expected: [1, 2, 3, 5] }, { args: [[1], 1], expected: [] }, { args: [[1, 2], 1], expected: [1] }] },
  },
  {
    id: "linked-lists:delete-value",
    topic: "linked-lists",
    title: "Delete All Matching Nodes",
    difficulty: "easy",
    statement: "Remove every node equal to a target value and return the remaining values. (List of values.)",
    examples: [{ input: "[1, 2, 3, 2, 1], target = 2", output: "[1, 3, 1]" }],
    approachQuiz: { prompt: "Safely delete nodes while walking?", options: ["Relink previous past the match", "Swap to the end", "Sort first"], answer: "Relink previous past the match", explain: "Point the previous node's next past the matched node — a dummy head simplifies the head case." },
    hints: ["Keep the previous node so you can relink.", "A dummy head node avoids special-casing the head.", "Skip nodes whose value matches."],
    approach: "Walk with a previous pointer (use a dummy head). When a node matches the target, set prev.next to node.next to unlink it. (As a list: keep the non-matching values.)",
    pythonCode: ["def delete_val(vals, target):", "    return [x for x in vals if x != target]"],
    complexity: { time: "O(n)", space: "O(1)" },
    takeaway: "Use a dummy head + relink-previous to delete nodes cleanly.",
    code: { starter: "def delete_val(vals, target):\n    # remove all nodes equal to target\n    pass", functionName: "delete_val", tests: [{ args: [[1, 2, 3, 2, 1], 2], expected: [1, 3, 1] }, { args: [[7, 7, 7], 7], expected: [] }, { args: [[1, 2], 5], expected: [1, 2] }] },
  },
  {
    id: "linked-lists:nth-node",
    topic: "linked-lists",
    title: "Value at Position k",
    difficulty: "easy",
    statement: "Return the value of the node at index k (0-indexed), or None if k is out of range. (List of values.)",
    examples: [{ input: "[10, 20, 30], k = 1", output: "20" }],
    approachQuiz: { prompt: "Why is this O(n), not O(1) like an array?", options: ["You must walk node by node", "Lists are unsorted", "It needs a hash map"], answer: "You must walk node by node", explain: "Linked lists have no indexing — you follow next links k times." },
    hints: ["There's no random access in a linked list.", "Walk forward k times from the head.", "Guard against k being out of range."],
    approach: "Step from the head k times following next links; return that node's value, or None if you run off the end.",
    pythonCode: ["def nth(vals, k):", "    if k < 0 or k >= len(vals):", "        return None", "    return vals[k]"],
    complexity: { time: "O(k)", space: "O(1)" },
    takeaway: "Linked lists have no indexing — reaching position k is O(k).",
    code: { starter: "def nth(vals, k):\n    # value at index k, or None\n    pass", functionName: "nth", tests: [{ args: [[10, 20, 30], 1], expected: 20 }, { args: [[10], 5], expected: null }, { args: [[1, 2, 3], 0], expected: 1 }] },
  },
];
