"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const recursionProblems: DsaProblem[] = [
  {
    id: "recursion:factorial",
    topic: "recursion",
    title: "Factorial",
    difficulty: "easy",
    statement: "Return n! (n factorial) using recursion. By definition, 0! = 1.",
    examples: [{ input: "5", output: "120" }],
    approachQuiz: { prompt: "What's the base case for factorial?", options: ["n <= 1 returns 1", "n == 0 returns 0", "There isn't one"], answer: "n <= 1 returns 1", explain: "0! and 1! are both 1 — that stops the recursion." },
    hints: ["n! = n × (n-1)!", "What's the smallest case you can answer directly?", "0! = 1! = 1 — stop there."],
    approach: "Base case: if n ≤ 1 return 1. Otherwise return n × factorial(n-1).",
    pythonCode: ["def factorial(n):", "    if n <= 1:", "        return 1", "    return n * factorial(n - 1)"],
    complexity: { time: "O(n)", space: "O(n) call stack" },
    takeaway: "Recursion = base case + a smaller self-call. factorial: n × (n-1)!.",
    code: { starter: "def factorial(n):\n    # return n! recursively\n    pass", functionName: "factorial", tests: [{ args: [5], expected: 120 }, { args: [0], expected: 1 }, { args: [1], expected: 1 }] },
  },
  {
    id: "recursion:fib",
    topic: "recursion",
    title: "Fibonacci Number",
    difficulty: "easy",
    statement: "Return the n-th Fibonacci number (0-indexed): fib(0)=0, fib(1)=1, then each is the sum of the previous two.",
    examples: [{ input: "7", output: "13" }],
    approachQuiz: { prompt: "Fibonacci's recurrence is…", options: ["fib(n) = fib(n-1) + fib(n-2)", "fib(n) = n × fib(n-1)", "fib(n) = 2 × fib(n-1)"], answer: "fib(n) = fib(n-1) + fib(n-2)", explain: "Two base cases (0 and 1), then sum the previous two." },
    hints: ["There are TWO base cases here.", "fib(0)=0 and fib(1)=1.", "Otherwise add the two before it."],
    approach: "Base cases: return n when n < 2. Otherwise return fib(n-1) + fib(n-2). (Memoise to avoid exponential blowup — that's DP!)",
    pythonCode: ["def fib(n):", "    if n < 2:", "        return n", "    return fib(n - 1) + fib(n - 2)"],
    complexity: { time: "O(2ⁿ) naive, O(n) memoised", space: "O(n)" },
    takeaway: "Two base cases; memoise the recurrence to make it O(n) (DP).",
    code: { starter: "def fib(n):\n    # return the nth Fibonacci number (0-indexed)\n    pass", functionName: "fib", tests: [{ args: [7], expected: 13 }, { args: [0], expected: 0 }, { args: [10], expected: 55 }] },
  },
  {
    id: "recursion:sum-digits",
    topic: "recursion",
    title: "Sum of Digits",
    difficulty: "easy",
    statement: "Return the sum of the digits of a non-negative integer, using recursion.",
    examples: [{ input: "1234", output: "10" }],
    approachQuiz: { prompt: "How do you peel off one digit?", options: ["n % 10 (last) and n // 10 (rest)", "n / 2", "str(n) only"], answer: "n % 10 (last) and n // 10 (rest)", explain: "% 10 gives the last digit; // 10 drops it — recurse on the rest." },
    hints: ["The last digit is n % 10.", "The remaining number is n // 10.", "Base case: a single digit returns itself."],
    approach: "Base case: if n < 10 return n. Otherwise return (n % 10) + sum_digits(n // 10).",
    pythonCode: ["def sum_digits(n):", "    if n < 10:", "        return n", "    return n % 10 + sum_digits(n // 10)"],
    complexity: { time: "O(d) digits", space: "O(d)" },
    takeaway: "Peel digits with % 10 and // 10; recurse on the shrinking number.",
    code: { starter: "def sum_digits(n):\n    # sum the digits recursively\n    pass", functionName: "sum_digits", tests: [{ args: [1234], expected: 10 }, { args: [5], expected: 5 }, { args: [99], expected: 18 }] },
  },
  {
    id: "recursion:power",
    topic: "recursion",
    title: "Power (bᵉ)",
    difficulty: "medium",
    statement: "Compute b raised to the power e (e ≥ 0) using recursion, without the ** operator.",
    examples: [{ input: "b = 2, e = 10", output: "1024" }],
    approachQuiz: { prompt: "Base case for exponent e?", options: ["e == 0 returns 1", "e == 1 returns 0", "No base case"], answer: "e == 0 returns 1", explain: "Anything to the power 0 is 1 — that ends the recursion." },
    hints: ["bᵉ = b × bᵉ⁻¹.", "What is b⁰?", "Return 1 when the exponent hits 0."],
    approach: "Base case: e == 0 returns 1. Otherwise return b × power(b, e-1). (Fast exponentiation halves e for O(log e).)",
    pythonCode: ["def power(b, e):", "    if e == 0:", "        return 1", "    return b * power(b, e - 1)"],
    complexity: { time: "O(e), O(log e) fast-exp", space: "O(e)" },
    takeaway: "bᵉ = b × bᵉ⁻¹, base case e=0 → 1; halving e gives O(log e).",
    code: { starter: "def power(b, e):\n    # return b ** e recursively (no ** operator)\n    pass", functionName: "power", tests: [{ args: [2, 10], expected: 1024 }, { args: [5, 0], expected: 1 }, { args: [3, 3], expected: 27 }] },
  },
  {
    id: "recursion:gcd",
    topic: "recursion",
    title: "Greatest Common Divisor",
    difficulty: "medium",
    statement: "Return the greatest common divisor of a and b using Euclid's algorithm (recursion).",
    examples: [{ input: "48, 18", output: "6" }],
    approachQuiz: { prompt: "Euclid's GCD recurrence?", options: ["gcd(a, b) = gcd(b, a % b)", "gcd(a, b) = a - b", "gcd(a, b) = a × b"], answer: "gcd(a, b) = gcd(b, a % b)", explain: "Replace the pair with (b, a mod b); when b hits 0, a is the GCD." },
    hints: ["The GCD of a and b equals the GCD of b and (a mod b).", "Keep taking remainders.", "When the second number is 0, the first is the answer."],
    approach: "Base case: if b == 0 return a. Otherwise return gcd(b, a % b). The remainder shrinks fast, so it's very efficient.",
    pythonCode: ["def gcd(a, b):", "    if b == 0:", "        return a", "    return gcd(b, a % b)"],
    complexity: { time: "O(log min(a, b))", space: "O(log min(a, b))" },
    takeaway: "Euclid: gcd(a, b) = gcd(b, a % b), base case b == 0 → a.",
    code: { starter: "def gcd(a, b):\n    # greatest common divisor (Euclid)\n    pass", functionName: "gcd", tests: [{ args: [48, 18], expected: 6 }, { args: [100, 10], expected: 10 }, { args: [7, 5], expected: 1 }] },
  },
];
