"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const stacksQueuesProblems: DsaProblem[] = [
  {
    id: "stacks-queues:valid-parens",
    topic: "stacks-queues",
    title: "Valid Parentheses",
    difficulty: "easy",
    statement: "Given a string of brackets ()[]{}, return True if every opener has a matching, correctly-ordered closer.",
    examples: [{ input: '"()[]{}"', output: "true" }, { input: '"([)]"', output: "false" }],
    approachQuiz: { prompt: "Match nested brackets with…", options: ["A stack", "A queue", "Binary search"], answer: "A stack", explain: "Push openers; each closer must match the most recent opener — that's LIFO." },
    hints: ["The most recent opener must close first.", "Push opening brackets onto a stack.", "On a closer, pop and check it matches; the stack must end empty."],
    approach: "Push each opening bracket. For each closing bracket, the top of the stack must be its matching opener — pop it. At the end the stack must be empty.",
    pythonCode: ["def is_valid(s):", "    pairs = {')': '(', ']': '[', '}': '{'}", "    stack = []", "    for c in s:", "        if c in '([{':", "            stack.append(c)", "        else:", "            if not stack or stack.pop() != pairs[c]:", "                return False", "    return not stack"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Balanced brackets = a stack: push openers, match on close, end empty.",
    code: { starter: "def is_valid(s):\n    # True if brackets are balanced and ordered\n    pass", functionName: "is_valid", tests: [{ args: ["()[]{}"], expected: true }, { args: ["(]"], expected: false }, { args: ["([)]"], expected: false }, { args: ["((("], expected: false }] },
  },
  {
    id: "stacks-queues:remove-adjacent",
    topic: "stacks-queues",
    title: "Remove Adjacent Duplicates",
    difficulty: "easy",
    statement: "Repeatedly remove two adjacent equal characters until none remain; return the final string.",
    examples: [{ input: '"abbaca"', output: '"ca"', note: "remove bb → aaca → remove aa → ca" }],
    approachQuiz: { prompt: "Cancel adjacent pairs efficiently?", options: ["A stack", "Sort the string", "Two pointers from ends"], answer: "A stack", explain: "If the next char equals the stack top, pop it — they cancel." },
    hints: ["Process characters left to right.", "Compare each with the top of a stack.", "Equal? Pop (they cancel). Otherwise push."],
    approach: "Push characters onto a stack; if the incoming char equals the top, pop instead (they cancel). The stack spells the answer.",
    pythonCode: ["def remove_adjacent(s):", "    stack = []", "    for c in s:", "        if stack and stack[-1] == c:", "            stack.pop()", "        else:", "            stack.append(c)", "    return ''.join(stack)"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Adjacent cancellation is a stack: pop when the top matches.",
    code: { starter: "def remove_adjacent(s):\n    # cancel adjacent equal chars; return the result\n    pass", functionName: "remove_adjacent", tests: [{ args: ["abbaca"], expected: "ca" }, { args: ["azxxzy"], expected: "ay" }, { args: ["aa"], expected: "" }] },
  },
  {
    id: "stacks-queues:eval-rpn",
    topic: "stacks-queues",
    title: "Evaluate Reverse Polish Notation",
    difficulty: "medium",
    statement: "Evaluate an arithmetic expression in Reverse Polish Notation (operators come after operands). Division truncates toward zero.",
    examples: [{ input: '["2","1","+","3","*"]', output: "9", note: "(2+1)*3" }],
    approachQuiz: { prompt: "Evaluate postfix expressions with…", options: ["A stack", "Recursion only", "A queue"], answer: "A stack", explain: "Push numbers; an operator pops the two most recent operands." },
    hints: ["Push numbers as you read them.", "On an operator, pop the last two numbers.", "Apply the operator and push the result back."],
    approach: "Scan tokens: push numbers; when you hit an operator, pop two operands, apply it, and push the result. The final stack value is the answer.",
    pythonCode: ["def eval_rpn(tokens):", "    stack = []", "    for t in tokens:", "        if t in ('+','-','*','/'):", "            b = stack.pop(); a = stack.pop()", "            if t == '+': stack.append(a + b)", "            elif t == '-': stack.append(a - b)", "            elif t == '*': stack.append(a * b)", "            else: stack.append(int(a / b))", "        else:", "            stack.append(int(t))", "    return stack[0]"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Postfix evaluation is a stack: operator pops its two operands.",
    code: { starter: "def eval_rpn(tokens):\n    # evaluate the RPN expression; return an int\n    pass", functionName: "eval_rpn", tests: [{ args: [["2", "1", "+", "3", "*"]], expected: 9 }, { args: [["4", "13", "5", "/", "+"]], expected: 6 }, { args: [["5"]], expected: 5 }] },
  },
  {
    id: "stacks-queues:next-greater",
    topic: "stacks-queues",
    title: "Next Greater Element",
    difficulty: "medium",
    statement: "For each element, find the next element to its right that is greater. If none, use -1.",
    examples: [{ input: "[2, 1, 2, 4, 3]", output: "[4, 2, 4, -1, -1]" }],
    approachQuiz: { prompt: "Find next-greater for all in O(n)?", options: ["A monotonic stack", "Nested loops", "Binary search"], answer: "A monotonic stack", explain: "Keep indices waiting for a greater value; resolve them when one appears." },
    hints: ["Keep a stack of indices still waiting for an answer.", "When a bigger number arrives, it answers everything smaller on top.", "Pop and fill those in."],
    approach: "Keep a stack of indices whose answer is unknown. For each new value, pop every index whose value is smaller (its next-greater is this value). Push the current index.",
    pythonCode: ["def next_greater(arr):", "    res = [-1] * len(arr)", "    stack = []", "    for i, x in enumerate(arr):", "        while stack and arr[stack[-1]] < x:", "            res[stack.pop()] = x", "        stack.append(i)", "    return res"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Monotonic stack: hold pending indices, resolve when a bigger value arrives.",
    code: { starter: "def next_greater(arr):\n    # next greater element to the right, else -1\n    pass", functionName: "next_greater", tests: [{ args: [[2, 1, 2, 4, 3]], expected: [4, 2, 4, -1, -1] }, { args: [[1, 2, 3]], expected: [2, 3, -1] }, { args: [[3, 2, 1]], expected: [-1, -1, -1] }] },
  },
  {
    id: "stacks-queues:daily-temps",
    topic: "stacks-queues",
    title: "Days Until Warmer",
    difficulty: "medium",
    statement: "For each day's temperature, return how many days until a warmer one. If none, use 0.",
    examples: [{ input: "[73, 74, 75, 71, 69, 72, 76, 73]", output: "[1, 1, 4, 2, 1, 1, 0, 0]" }],
    approachQuiz: { prompt: "Same pattern as next-greater?", options: ["Yes — a monotonic stack of days", "No — needs sorting", "No — binary search"], answer: "Yes — a monotonic stack of days", explain: "Store day indices; a warmer day resolves all cooler days waiting on the stack." },
    hints: ["Store indices of days still waiting for a warmer one.", "When today is warmer than the stack top's day, you found its answer.", "The gap is the number of days."],
    approach: "Monotonic stack of day indices. For each day, while it's warmer than the day on top, pop and record the day difference. Push the current day.",
    pythonCode: ["def days_until_warmer(temps):", "    res = [0] * len(temps)", "    stack = []", "    for i, t in enumerate(temps):", "        while stack and temps[stack[-1]] < t:", "            j = stack.pop()", "            res[j] = i - j", "        stack.append(i)", "    return res"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Same monotonic-stack pattern as next-greater, storing indices for gaps.",
    code: { starter: "def days_until_warmer(temps):\n    # days until a warmer temperature, else 0\n    pass", functionName: "days_until_warmer", tests: [{ args: [[73, 74, 75, 71, 69, 72, 76, 73]], expected: [1, 1, 4, 2, 1, 1, 0, 0] }, { args: [[30, 40, 50]], expected: [1, 1, 0] }, { args: [[50, 40, 30]], expected: [0, 0, 0] }] },
  },
];
