"use client";

import type { DsaProblem } from "@/lib/dsa/types";

// Trees are nested lists: a node is [value, left, right]; empty = None.

const TREE = [1, [2, [4, null, null], [5, null, null]], [3, null, null]];

export const treeTraversalsProblems: DsaProblem[] = [
  {
    id: "tree-traversals:inorder",
    topic: "tree-traversals",
    title: "In-order Traversal",
    difficulty: "easy",
    statement: "Return the values in IN-ORDER: left subtree, then the node, then the right subtree. (Node = [value, left, right].)",
    examples: [{ input: "[1,[2,[4,_,_],[5,_,_]],[3,_,_]]", output: "[4, 2, 5, 1, 3]" }],
    approachQuiz: { prompt: "In-order means…", options: ["Left, Node, Right", "Node, Left, Right", "Left, Right, Node"], answer: "Left, Node, Right", explain: "On a BST this yields sorted order." },
    hints: ["Recurse into the left subtree first.", "Then record this node.", "Then recurse into the right subtree."],
    approach: "Base case None → []. Otherwise inorder(left) + [value] + inorder(right).",
    pythonCode: ["def inorder(node):", "    if node is None:", "        return []", "    return inorder(node[1]) + [node[0]] + inorder(node[2])"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "In-order = Left, Node, Right → sorted output on a BST.",
    code: { starter: "def inorder(node):\n    # return values in in-order\n    pass", functionName: "inorder", tests: [{ args: [TREE], expected: [4, 2, 5, 1, 3] }, { args: [null], expected: [] }, { args: [[1, null, null]], expected: [1] }] },
  },
  {
    id: "tree-traversals:preorder",
    topic: "tree-traversals",
    title: "Pre-order Traversal",
    difficulty: "easy",
    statement: "Return the values in PRE-ORDER: the node first, then left subtree, then right subtree.",
    examples: [{ input: "the sample tree", output: "[1, 2, 4, 5, 3]" }],
    approachQuiz: { prompt: "Pre-order means…", options: ["Node, Left, Right", "Left, Node, Right", "Left, Right, Node"], answer: "Node, Left, Right", explain: "Node first — handy for copying/serialising a tree." },
    hints: ["Record this node before its children.", "Then recurse left.", "Then recurse right."],
    approach: "Base case None → []. Otherwise [value] + preorder(left) + preorder(right).",
    pythonCode: ["def preorder(node):", "    if node is None:", "        return []", "    return [node[0]] + preorder(node[1]) + preorder(node[2])"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "Pre-order = Node first — good for copying a tree.",
    code: { starter: "def preorder(node):\n    # return values in pre-order\n    pass", functionName: "preorder", tests: [{ args: [TREE], expected: [1, 2, 4, 5, 3] }, { args: [null], expected: [] }] },
  },
  {
    id: "tree-traversals:postorder",
    topic: "tree-traversals",
    title: "Post-order Traversal",
    difficulty: "easy",
    statement: "Return the values in POST-ORDER: left subtree, then right subtree, then the node last.",
    examples: [{ input: "the sample tree", output: "[4, 5, 2, 3, 1]" }],
    approachQuiz: { prompt: "Post-order means…", options: ["Left, Right, Node", "Node, Left, Right", "Left, Node, Right"], answer: "Left, Right, Node", explain: "Node last — the safe order to free/fold a tree bottom-up." },
    hints: ["Process both children before the node.", "Recurse left, then right.", "Record the node last."],
    approach: "Base case None → []. Otherwise postorder(left) + postorder(right) + [value].",
    pythonCode: ["def postorder(node):", "    if node is None:", "        return []", "    return postorder(node[1]) + postorder(node[2]) + [node[0]]"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "Post-order = Node last — safe for deleting/folding a tree.",
    code: { starter: "def postorder(node):\n    # return values in post-order\n    pass", functionName: "postorder", tests: [{ args: [TREE], expected: [4, 5, 2, 3, 1] }, { args: [[1, null, null]], expected: [1] }] },
  },
  {
    id: "tree-traversals:level-order",
    topic: "tree-traversals",
    title: "Level-order (BFS) Traversal",
    difficulty: "medium",
    statement: "Return the values level by level, left to right (breadth-first).",
    examples: [{ input: "the sample tree", output: "[1, 2, 3, 4, 5]" }],
    approachQuiz: { prompt: "Visit a tree level by level with…", options: ["A queue", "A stack", "Recursion only"], answer: "A queue", explain: "BFS uses a FIFO queue: dequeue a node, enqueue its children." },
    hints: ["This is breadth-first, not depth-first.", "Use a queue.", "Dequeue a node, record it, enqueue its children."],
    approach: "Start a queue with the root. Repeatedly dequeue a node, record its value, and enqueue its non-empty children.",
    pythonCode: ["def level_order(node):", "    from collections import deque", "    if node is None:", "        return []", "    q = deque([node]); out = []", "    while q:", "        n = q.popleft(); out.append(n[0])", "        if n[1] is not None: q.append(n[1])", "        if n[2] is not None: q.append(n[2])", "    return out"],
    complexity: { time: "O(n)", space: "O(n)" },
    takeaway: "Level-order = BFS with a queue (dequeue node, enqueue children).",
    code: { starter: "def level_order(node):\n    # return values level by level\n    pass", functionName: "level_order", tests: [{ args: [TREE], expected: [1, 2, 3, 4, 5] }, { args: [null], expected: [] }] },
  },
  {
    id: "tree-traversals:leaves",
    topic: "tree-traversals",
    title: "Collect the Leaves",
    difficulty: "easy",
    statement: "Return the leaf values (nodes with no children) from left to right.",
    examples: [{ input: "the sample tree", output: "[4, 5, 3]" }],
    approachQuiz: { prompt: "A leaf is a node that…", options: ["Has no children", "Has one child", "Is the root"], answer: "Has no children", explain: "Both left and right are None." },
    hints: ["A leaf has no left and no right child.", "Recurse into both subtrees.", "Collect a node only when it's a leaf."],
    approach: "Base case None → []. If both children are None it's a leaf → [value]. Otherwise combine the leaves of both subtrees.",
    pythonCode: ["def leaf_values(node):", "    if node is None:", "        return []", "    if node[1] is None and node[2] is None:", "        return [node[0]]", "    return leaf_values(node[1]) + leaf_values(node[2])"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "A leaf has no children — collect them left to right with recursion.",
    code: { starter: "def leaf_values(node):\n    # return leaf values, left to right\n    pass", functionName: "leaf_values", tests: [{ args: [TREE], expected: [4, 5, 3] }, { args: [[1, null, null]], expected: [1] }] },
  },
];
