"use client";

import type { DsaProblem } from "@/lib/dsa/types";

// Trees are given as nested lists: a node is [value, left, right]; empty = None.
// e.g. [5, [3, [1, None, None], None], [8, None, None]]

export const treesBstProblems: DsaProblem[] = [
  {
    id: "trees-bst:count-nodes",
    topic: "trees-bst",
    title: "Count the Nodes",
    difficulty: "easy",
    statement: "Count the nodes in a binary tree. A node is [value, left, right]; an empty subtree is None.",
    examples: [{ input: "[5, [3, [1,None,None], None], [8,None,None]]", output: "4" }],
    approachQuiz: { prompt: "Count a tree's nodes?", options: ["1 + count(left) + count(right)", "Just count the root", "Sort the values"], answer: "1 + count(left) + count(right)", explain: "Tree recursion: this node plus both subtrees." },
    hints: ["The empty tree (None) has 0 nodes.", "Otherwise it's this node…", "…plus the counts of the left and right subtrees."],
    approach: "Base case: None → 0. Otherwise return 1 + count of left + count of right.",
    pythonCode: ["def count_nodes(node):", "    if node is None:", "        return 0", "    return 1 + count_nodes(node[1]) + count_nodes(node[2])"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "Tree recursion: combine the answers from both subtrees + the node.",
    code: { starter: "def count_nodes(node):\n    # node is [value, left, right] or None\n    pass", functionName: "count_nodes", tests: [{ args: [[5, [3, [1, null, null], null], [8, null, null]]], expected: 4 }, { args: [null], expected: 0 }, { args: [[1, null, null]], expected: 1 }] },
  },
  {
    id: "trees-bst:height",
    topic: "trees-bst",
    title: "Tree Height",
    difficulty: "easy",
    statement: "Return the height of a binary tree = the number of nodes on the longest root-to-leaf path. Empty tree = 0.",
    examples: [{ input: "[1, [2,None,None], None]", output: "2" }],
    approachQuiz: { prompt: "Height of a tree?", options: ["1 + max(left, right) heights", "left + right heights", "count of nodes"], answer: "1 + max(left, right) heights", explain: "The longer of the two subtrees, plus this level." },
    hints: ["Empty tree has height 0.", "A node adds 1 to the taller subtree.", "Use max of the two subtree heights."],
    approach: "Base case: None → 0. Otherwise 1 + max(height(left), height(right)).",
    pythonCode: ["def tree_height(node):", "    if node is None:", "        return 0", "    return 1 + max(tree_height(node[1]), tree_height(node[2]))"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "Height = 1 + the taller subtree; empty = 0.",
    code: { starter: "def tree_height(node):\n    # longest root-to-leaf node count\n    pass", functionName: "tree_height", tests: [{ args: [[1, [2, null, null], null]], expected: 2 }, { args: [null], expected: 0 }, { args: [[5, [3, [1, null, null], null], [8, null, null]]], expected: 3 }] },
  },
  {
    id: "trees-bst:sum",
    topic: "trees-bst",
    title: "Sum of All Nodes",
    difficulty: "easy",
    statement: "Return the sum of every value in the binary tree.",
    examples: [{ input: "[5, [3,None,None], [8,None,None]]", output: "16" }],
    approachQuiz: { prompt: "Sum a tree?", options: ["node + sum(left) + sum(right)", "Only leaves", "Sort then sum"], answer: "node + sum(left) + sum(right)", explain: "Add this node to the sums of both subtrees." },
    hints: ["Empty subtree contributes 0.", "Add this node's value…", "…to the sums of both children."],
    approach: "Base case None → 0. Otherwise node value + sum(left) + sum(right).",
    pythonCode: ["def tree_sum(node):", "    if node is None:", "        return 0", "    return node[0] + tree_sum(node[1]) + tree_sum(node[2])"],
    complexity: { time: "O(n)", space: "O(h)" },
    takeaway: "Aggregate a tree by combining subtree results with the node.",
    code: { starter: "def tree_sum(node):\n    # sum every value in the tree\n    pass", functionName: "tree_sum", tests: [{ args: [[5, [3, null, null], [8, null, null]]], expected: 16 }, { args: [null], expected: 0 }, { args: [[5, [3, [1, null, null], null], [8, null, null]]], expected: 17 }] },
  },
  {
    id: "trees-bst:search",
    topic: "trees-bst",
    title: "BST Search",
    difficulty: "medium",
    statement: "Return True if a target value exists in a Binary Search Tree (smaller values left, bigger right).",
    examples: [{ input: "tree, target = 8", output: "true" }],
    approachQuiz: { prompt: "Search a BST?", options: ["Go left if smaller, right if bigger", "Check every node", "Sort first"], answer: "Go left if smaller, right if bigger", explain: "The BST order lets you discard half each step — O(h)." },
    hints: ["Compare the target to the current node.", "Smaller → go left; bigger → go right.", "Equal → found; None → not here."],
    approach: "At each node: equal → True. If target < node, search left; else search right. None → False.",
    pythonCode: ["def bst_search(node, target):", "    if node is None:", "        return False", "    if node[0] == target:", "        return True", "    if target < node[0]:", "        return bst_search(node[1], target)", "    return bst_search(node[2], target)"],
    complexity: { time: "O(h)", space: "O(h)" },
    takeaway: "BST search uses the ordering to skip half the tree each step.",
    code: { starter: "def bst_search(node, target):\n    # True if target is in the BST\n    pass", functionName: "bst_search", tests: [{ args: [[5, [3, [1, null, null], null], [8, null, null]], 8], expected: true }, { args: [[5, [3, [1, null, null], null], [8, null, null]], 4], expected: false }, { args: [null, 1], expected: false }] },
  },
  {
    id: "trees-bst:min",
    topic: "trees-bst",
    title: "Smallest Value in a BST",
    difficulty: "easy",
    statement: "Return the smallest value in a non-empty Binary Search Tree.",
    examples: [{ input: "tree", output: "1" }],
    approachQuiz: { prompt: "Where's the min in a BST?", options: ["Keep going left", "Keep going right", "At the root"], answer: "Keep going left", explain: "Smaller values are always to the left — the leftmost node is the minimum." },
    hints: ["Smaller goes left in a BST.", "So the smallest is as far left as possible.", "Walk left until there's no left child."],
    approach: "Follow left children until there is no left child; that node holds the minimum.",
    pythonCode: ["def bst_min(node):", "    while node[1] is not None:", "        node = node[1]", "    return node[0]"],
    complexity: { time: "O(h)", space: "O(1)" },
    takeaway: "BST minimum = the leftmost node; maximum = the rightmost.",
    code: { starter: "def bst_min(node):\n    # smallest value in the BST\n    pass", functionName: "bst_min", tests: [{ args: [[5, [3, [1, null, null], null], [8, null, null]]], expected: 1 }, { args: [[10, null, null]], expected: 10 }] },
  },
];
