"use client";

import type { DsaProblem } from "@/lib/dsa/types";

export const triesProblems: DsaProblem[] = [
  {
    id: "tries:has-word",
    topic: "tries",
    title: "Word Exists?",
    difficulty: "easy",
    statement: "Given a dictionary of words and a target, return True if the exact word is in the dictionary.",
    examples: [{ input: '["cat","car","dog"], "car"', output: "true" }],
    approachQuiz: { prompt: "A trie stores words…", options: ["Letter by letter, sharing prefixes", "Sorted in an array", "In a heap"], answer: "Letter by letter, sharing prefixes", explain: "Each path of characters spells a word; an end-marker flags complete words." },
    hints: ["Walk the trie one character at a time.", "If any character's branch is missing, it's not there.", "The final node must be marked as a word end."],
    approach: "With a trie: follow each character; if a branch is missing return False; at the end check the word-end flag. (As a set: membership.)",
    pythonCode: ["def has_word(words, target):", "    return target in set(words)"],
    complexity: { time: "O(L) with a trie", space: "O(total chars)" },
    takeaway: "Tries store words letter-by-letter; lookup is O(word length).",
    code: { starter: "def has_word(words, target):\n    # True if target is in the dictionary\n    pass", functionName: "has_word", tests: [{ args: [["cat", "car", "dog"], "car"], expected: true }, { args: [["cat", "car", "dog"], "cow"], expected: false }, { args: [["ca"], "cat"], expected: false }] },
  },
  {
    id: "tries:count-prefix",
    topic: "tries",
    title: "Count Words With Prefix",
    difficulty: "medium",
    statement: "Return how many dictionary words start with a given prefix.",
    examples: [{ input: '["cat","car","dog"], "ca"', output: "2" }],
    approachQuiz: { prompt: "Why are tries great for prefixes?", options: ["Shared prefixes share one branch", "They sort words", "They use less memory than a set"], answer: "Shared prefixes share one branch", explain: "Walk to the prefix node once; everything below it shares that start." },
    hints: ["You only care about the start of each word.", "Walk down the prefix path in the trie.", "Count the words in the subtree below it."],
    approach: "With a trie: descend to the prefix node, then count word-ends in its subtree. (As strings: count words that start with the prefix.)",
    pythonCode: ["def count_prefix(words, prefix):", "    return sum(1 for w in words if w.startswith(prefix))"],
    complexity: { time: "O(words × L)", space: "O(total chars)" },
    takeaway: "Tries answer 'starts with…' fast because prefixes are shared.",
    code: { starter: "def count_prefix(words, prefix):\n    # how many words start with prefix\n    pass", functionName: "count_prefix", tests: [{ args: [["cat", "car", "dog"], "ca"], expected: 2 }, { args: [["cat", "car", "dog"], "do"], expected: 1 }, { args: [["cat"], "z"], expected: 0 }] },
  },
  {
    id: "tries:lcp",
    topic: "tries",
    title: "Longest Common Prefix",
    difficulty: "medium",
    statement: "Return the longest prefix shared by ALL the words ('' if none).",
    examples: [{ input: '["flower","flow","flight"]', output: '"fl"' }],
    approachQuiz: { prompt: "Where's the common prefix in a trie?", options: ["The single chain before it branches", "The deepest leaf", "The root only"], answer: "The single chain before it branches", explain: "The shared prefix is the path until the first branch or word-end." },
    hints: ["Start with the first word as the candidate prefix.", "Trim it until every word starts with it.", "If it becomes empty, there's no common prefix."],
    approach: "With a trie: follow the single chain from the root until it branches or a word ends. (As strings: shrink a candidate prefix until all words share it.)",
    pythonCode: ["def longest_common_prefix(words):", "    if not words:", "        return ''", "    pre = words[0]", "    for w in words[1:]:", "        while not w.startswith(pre):", "            pre = pre[:-1]", "            if not pre:", "                return ''", "    return pre"],
    complexity: { time: "O(total chars)", space: "O(1)" },
    takeaway: "The common prefix is the trie's single chain before it branches.",
    code: { starter: "def longest_common_prefix(words):\n    # longest prefix shared by all words\n    pass", functionName: "longest_common_prefix", tests: [{ args: [["flower", "flow", "flight"]], expected: "fl" }, { args: [["dog", "cat"]], expected: "" }, { args: [["abc"]], expected: "abc" }] },
  },
  {
    id: "tries:autocomplete",
    topic: "tries",
    title: "Autocomplete",
    difficulty: "medium",
    statement: "Return all dictionary words that start with a prefix, sorted alphabetically.",
    examples: [{ input: '["cat","car","dog"], "ca"', output: '["car","cat"]' }],
    approachQuiz: { prompt: "Autocomplete = …", options: ["Walk to the prefix, collect everything below", "Sort all words", "Binary search"], answer: "Walk to the prefix, collect everything below", explain: "The subtree under the prefix node holds exactly the completions." },
    hints: ["First reach the prefix node.", "Then gather every word in its subtree.", "Return them sorted."],
    approach: "With a trie: descend to the prefix node, DFS the subtree collecting word-ends. (As strings: filter words by prefix, then sort.)",
    pythonCode: ["def autocomplete(words, prefix):", "    return sorted(w for w in words if w.startswith(prefix))"],
    complexity: { time: "O(words × L)", space: "O(matches)" },
    takeaway: "Autocomplete = prefix node + collect its subtree (sorted).",
    code: { starter: "def autocomplete(words, prefix):\n    # sorted words starting with prefix\n    pass", functionName: "autocomplete", tests: [{ args: [["cat", "car", "dog"], "ca"], expected: ["car", "cat"] }, { args: [["apple", "app", "apt"], "ap"], expected: ["app", "apple", "apt"] }, { args: [["x"], "y"], expected: [] }] },
  },
];
