/**
 * Role catalog powering programmatic SEO pages:
 *   /resume-checker/[role]      → "ATS Resume Checker for {Role}"
 *   /interview-questions/[role] → "Mock Interview Questions for {Role}"
 *
 * One template × every role here = hundreds of indexed, role-specific pages.
 * Keep `skills`/`tools` accurate — they drive the (non-thin) page content,
 * the ATS keyword lists, and the generated interview questions.
 */

export interface SeoRole {
  slug: string;
  name: string;
  category: string;
  /** Hard skills / ATS keywords a recruiter scans for. */
  skills: string[];
  /** Tools & technologies commonly required. */
  tools: string[];
  /** One-sentence description of what the role does. */
  blurb: string;
}

export const SEO_ROLES: SeoRole[] = [
  // ── Software Engineering ──────────────────────────────────────────────────
  { slug: "software-engineer", name: "Software Engineer", category: "Engineering",
    skills: ["Data structures", "Algorithms", "System design", "OOP", "REST APIs", "Unit testing", "Git"],
    tools: ["Java", "Python", "JavaScript", "Docker", "AWS", "PostgreSQL"],
    blurb: "Designs, builds, and maintains software systems across the stack." },
  { slug: "frontend-developer", name: "Frontend Developer", category: "Engineering",
    skills: ["HTML", "CSS", "JavaScript", "Responsive design", "Accessibility", "State management", "Web performance"],
    tools: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Vite", "Figma"],
    blurb: "Builds the user-facing parts of web applications." },
  { slug: "backend-developer", name: "Backend Developer", category: "Engineering",
    skills: ["API design", "Databases", "Authentication", "Caching", "Microservices", "Message queues"],
    tools: ["Node.js", "Python", "Go", "PostgreSQL", "Redis", "Docker"],
    blurb: "Builds server-side logic, APIs, and data layers." },
  { slug: "full-stack-developer", name: "Full Stack Developer", category: "Engineering",
    skills: ["Frontend", "Backend", "Databases", "REST APIs", "CI/CD", "System design"],
    tools: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker"],
    blurb: "Works across both frontend and backend of an application." },
  { slug: "react-developer", name: "React Developer", category: "Engineering",
    skills: ["React", "Hooks", "State management", "Component design", "Web performance", "Testing"],
    tools: ["React", "Redux", "Next.js", "TypeScript", "Jest", "Tailwind CSS"],
    blurb: "Specialises in building UIs with React and its ecosystem." },
  { slug: "python-developer", name: "Python Developer", category: "Engineering",
    skills: ["Python", "OOP", "REST APIs", "Testing", "Async programming", "Data structures"],
    tools: ["Django", "FastAPI", "Flask", "PostgreSQL", "Celery", "Docker"],
    blurb: "Builds applications and services primarily in Python." },
  { slug: "java-developer", name: "Java Developer", category: "Engineering",
    skills: ["Java", "Spring", "OOP", "Multithreading", "JVM internals", "REST APIs", "Microservices"],
    tools: ["Spring Boot", "Hibernate", "Maven", "Kafka", "PostgreSQL", "Docker"],
    blurb: "Builds enterprise-grade backend systems in Java." },
  { slug: "mobile-developer", name: "Mobile Developer", category: "Engineering",
    skills: ["Mobile UI", "State management", "Offline storage", "Push notifications", "App lifecycle"],
    tools: ["React Native", "Flutter", "Swift", "Kotlin", "Firebase"],
    blurb: "Builds native or cross-platform mobile applications." },
  { slug: "devops-engineer", name: "DevOps Engineer", category: "Engineering",
    skills: ["CI/CD", "Infrastructure as Code", "Monitoring", "Containerisation", "Cloud architecture", "Scripting"],
    tools: ["Docker", "Kubernetes", "Terraform", "AWS", "Jenkins", "Prometheus"],
    blurb: "Automates build, deployment, and infrastructure operations." },
  { slug: "cloud-engineer", name: "Cloud Engineer", category: "Engineering",
    skills: ["Cloud architecture", "Networking", "Security", "Cost optimisation", "Infrastructure as Code"],
    tools: ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "CloudFormation"],
    blurb: "Designs and manages cloud infrastructure and services." },
  { slug: "qa-engineer", name: "QA Engineer", category: "Engineering",
    skills: ["Test planning", "Automation testing", "Regression testing", "Bug tracking", "API testing"],
    tools: ["Selenium", "Cypress", "Postman", "JIRA", "TestNG"],
    blurb: "Ensures software quality through manual and automated testing." },
  { slug: "cybersecurity-analyst", name: "Cybersecurity Analyst", category: "Engineering",
    skills: ["Threat detection", "Incident response", "Vulnerability assessment", "SIEM", "Network security"],
    tools: ["Wireshark", "Splunk", "Nmap", "Burp Suite", "Metasploit"],
    blurb: "Protects systems and networks from security threats." },

  // ── Data & AI ─────────────────────────────────────────────────────────────
  { slug: "data-analyst", name: "Data Analyst", category: "Data & Analytics",
    skills: ["SQL", "Data visualisation", "Statistics", "Excel", "Dashboarding", "A/B testing", "Storytelling with data"],
    tools: ["SQL", "Power BI", "Tableau", "Excel", "Python", "Looker"],
    blurb: "Turns raw data into insights that drive business decisions." },
  { slug: "data-scientist", name: "Data Scientist", category: "Data & Analytics",
    skills: ["Machine learning", "Statistics", "Feature engineering", "Model evaluation", "Experiment design", "SQL"],
    tools: ["Python", "pandas", "scikit-learn", "TensorFlow", "SQL", "Jupyter"],
    blurb: "Builds predictive models and extracts insight from data." },
  { slug: "data-engineer", name: "Data Engineer", category: "Data & Analytics",
    skills: ["ETL", "Data pipelines", "Data modelling", "SQL", "Distributed systems", "Streaming"],
    tools: ["Spark", "Airflow", "Kafka", "Snowflake", "dbt", "AWS"],
    blurb: "Builds and maintains pipelines that move and shape data." },
  { slug: "machine-learning-engineer", name: "Machine Learning Engineer", category: "Data & Analytics",
    skills: ["ML algorithms", "Model deployment", "MLOps", "Feature engineering", "Deep learning", "Python"],
    tools: ["PyTorch", "TensorFlow", "scikit-learn", "MLflow", "Docker", "Kubernetes"],
    blurb: "Productionises machine learning models at scale." },
  { slug: "business-analyst", name: "Business Analyst", category: "Data & Analytics",
    skills: ["Requirements gathering", "Process mapping", "Stakeholder management", "SQL", "Data analysis", "Documentation"],
    tools: ["Excel", "SQL", "Power BI", "JIRA", "Visio"],
    blurb: "Bridges business needs and technical solutions." },

  // ── Product & Design ────────────────────────────────────────────────────
  { slug: "product-manager", name: "Product Manager", category: "Product & Design",
    skills: ["Product strategy", "Roadmapping", "User research", "Prioritisation", "Stakeholder management", "Metrics & KPIs"],
    tools: ["JIRA", "Figma", "Amplitude", "Notion", "SQL"],
    blurb: "Owns the strategy, roadmap, and delivery of a product." },
  { slug: "project-manager", name: "Project Manager", category: "Product & Design",
    skills: ["Project planning", "Risk management", "Stakeholder communication", "Budgeting", "Agile", "Scheduling"],
    tools: ["JIRA", "MS Project", "Asana", "Confluence", "Excel"],
    blurb: "Plans, executes, and delivers projects on time and budget." },
  { slug: "ui-ux-designer", name: "UI/UX Designer", category: "Product & Design",
    skills: ["User research", "Wireframing", "Prototyping", "Interaction design", "Usability testing", "Design systems"],
    tools: ["Figma", "Sketch", "Adobe XD", "Framer", "Miro"],
    blurb: "Designs intuitive, user-centred product experiences." },
  { slug: "product-designer", name: "Product Designer", category: "Product & Design",
    skills: ["Visual design", "Interaction design", "Prototyping", "Design systems", "User research"],
    tools: ["Figma", "Sketch", "Framer", "Adobe Creative Suite"],
    blurb: "Owns the end-to-end design of product features." },
  { slug: "graphic-designer", name: "Graphic Designer", category: "Product & Design",
    skills: ["Typography", "Branding", "Layout", "Colour theory", "Visual hierarchy"],
    tools: ["Photoshop", "Illustrator", "InDesign", "Figma", "Canva"],
    blurb: "Creates visual content for brands and campaigns." },

  // ── Marketing & Content ───────────────────────────────────────────────────
  { slug: "digital-marketing-manager", name: "Digital Marketing Manager", category: "Marketing",
    skills: ["Campaign strategy", "SEO", "Paid ads", "Analytics", "Content marketing", "Conversion optimisation"],
    tools: ["Google Analytics", "Google Ads", "Meta Ads", "HubSpot", "SEMrush"],
    blurb: "Leads digital campaigns across channels to drive growth." },
  { slug: "seo-specialist", name: "SEO Specialist", category: "Marketing",
    skills: ["Keyword research", "On-page SEO", "Link building", "Technical SEO", "Content strategy", "Analytics"],
    tools: ["Google Search Console", "Ahrefs", "SEMrush", "Screaming Frog", "GA4"],
    blurb: "Improves organic search rankings and traffic." },
  { slug: "content-writer", name: "Content Writer", category: "Marketing",
    skills: ["Writing", "Editing", "SEO writing", "Research", "Storytelling", "Content strategy"],
    tools: ["Google Docs", "Grammarly", "WordPress", "Surfer SEO", "Notion"],
    blurb: "Creates written content that informs and converts." },

  // ── Sales & Customer ─────────────────────────────────────────────────────
  { slug: "sales-executive", name: "Sales Executive", category: "Sales & Customer",
    skills: ["Lead generation", "Negotiation", "CRM management", "Cold outreach", "Closing", "Pipeline management"],
    tools: ["Salesforce", "HubSpot", "LinkedIn Sales Navigator", "Outreach"],
    blurb: "Generates revenue by closing new business." },
  { slug: "account-manager", name: "Account Manager", category: "Sales & Customer",
    skills: ["Relationship management", "Upselling", "Negotiation", "Account planning", "Renewals"],
    tools: ["Salesforce", "HubSpot", "Gainsight", "Excel"],
    blurb: "Owns and grows relationships with existing clients." },
  { slug: "customer-success-manager", name: "Customer Success Manager", category: "Sales & Customer",
    skills: ["Onboarding", "Retention", "Relationship management", "Product adoption", "Churn reduction"],
    tools: ["Gainsight", "Intercom", "Salesforce", "Zendesk"],
    blurb: "Ensures customers achieve value and renew." },

  // ── Business & Operations ─────────────────────────────────────────────────
  { slug: "hr-manager", name: "HR Manager", category: "Business & Operations",
    skills: ["Talent management", "Employee relations", "Performance management", "HR policy", "Compensation"],
    tools: ["Workday", "BambooHR", "Excel", "Greenhouse"],
    blurb: "Leads people operations and HR strategy." },
  { slug: "recruiter", name: "Recruiter", category: "Business & Operations",
    skills: ["Sourcing", "Screening", "Interviewing", "Stakeholder management", "Employer branding", "ATS management"],
    tools: ["LinkedIn Recruiter", "Greenhouse", "Lever", "Naukri"],
    blurb: "Finds, screens, and hires talent for the organisation." },
  { slug: "finance-analyst", name: "Finance Analyst", category: "Business & Operations",
    skills: ["Financial modelling", "Forecasting", "Budgeting", "Variance analysis", "Excel", "Valuation"],
    tools: ["Excel", "SQL", "Power BI", "SAP", "Tableau"],
    blurb: "Analyses financial data to guide business decisions." },
  { slug: "accountant", name: "Accountant", category: "Business & Operations",
    skills: ["Bookkeeping", "Financial reporting", "Taxation", "Reconciliation", "GAAP", "Auditing"],
    tools: ["Tally", "QuickBooks", "SAP", "Excel", "Zoho Books"],
    blurb: "Maintains and reports on financial records." },
  { slug: "operations-manager", name: "Operations Manager", category: "Business & Operations",
    skills: ["Process optimisation", "Team leadership", "Supply chain", "KPI tracking", "Vendor management"],
    tools: ["Excel", "SAP", "Power BI", "JIRA"],
    blurb: "Oversees day-to-day operations and efficiency." },

  // ══════════════════════════════════════════════════════════════════════════
  // Expansion — India job market. Keep skills/tools accurate: they drive ATS
  // keyword lists and the generated interview questions on every role page.
  // ══════════════════════════════════════════════════════════════════════════

  // ── Engineering (expansion) ───────────────────────────────────────────────
  { slug: "android-developer", name: "Android Developer", category: "Engineering",
    skills: ["Android SDK", "Kotlin", "Jetpack Compose", "MVVM architecture", "REST API integration", "Material Design", "Play Store release"],
    tools: ["Kotlin", "Android Studio", "Jetpack Compose", "Retrofit", "Firebase", "Gradle"],
    blurb: "Builds native Android applications for phones and tablets." },
  { slug: "ios-developer", name: "iOS Developer", category: "Engineering",
    skills: ["Swift", "UIKit", "SwiftUI", "MVVM architecture", "Core Data", "Auto Layout", "App Store release"],
    tools: ["Swift", "Xcode", "SwiftUI", "Combine", "CocoaPods", "TestFlight"],
    blurb: "Builds native iOS applications for iPhone and iPad." },
  { slug: "flutter-developer", name: "Flutter Developer", category: "Engineering",
    skills: ["Dart", "Widget composition", "State management", "Platform channels", "Responsive layouts", "REST integration"],
    tools: ["Flutter", "Dart", "Bloc", "Riverpod", "Firebase", "Android Studio"],
    blurb: "Builds cross-platform mobile apps from a single Dart codebase." },
  { slug: "nodejs-developer", name: "Node.js Developer", category: "Engineering",
    skills: ["Node.js", "Express", "Async programming", "REST APIs", "Authentication", "Error handling", "NoSQL modelling"],
    tools: ["Node.js", "Express", "MongoDB", "Redis", "Jest", "Docker"],
    blurb: "Builds server-side applications and APIs on the Node.js runtime." },
  { slug: "dotnet-developer", name: ".NET Developer", category: "Engineering",
    skills: ["C#", ".NET Core", "ASP.NET MVC", "Entity Framework", "LINQ", "REST APIs", "OOP"],
    tools: ["C#", "ASP.NET Core", "Entity Framework", "SQL Server", "Azure", "Visual Studio"],
    blurb: "Builds enterprise web and service applications on the .NET stack." },
  { slug: "php-developer", name: "PHP Developer", category: "Engineering",
    skills: ["PHP", "MySQL", "MVC architecture", "REST APIs", "Session management", "Composer dependency management"],
    tools: ["Laravel", "MySQL", "Composer", "Apache", "Git", "phpMyAdmin"],
    blurb: "Builds and maintains web applications and CMS backends in PHP." },
  { slug: "golang-developer", name: "Golang Developer", category: "Engineering",
    skills: ["Go", "Goroutines", "Channels", "Concurrency patterns", "gRPC", "REST APIs", "Microservices"],
    tools: ["Go", "gRPC", "Docker", "Kubernetes", "PostgreSQL", "Prometheus"],
    blurb: "Builds high-concurrency backend services in Go." },
  { slug: "angular-developer", name: "Angular Developer", category: "Engineering",
    skills: ["Angular", "TypeScript", "RxJS", "Component architecture", "Dependency injection", "Reactive forms"],
    tools: ["Angular", "TypeScript", "RxJS", "NgRx", "Karma", "Angular CLI"],
    blurb: "Builds enterprise single-page applications with Angular." },
  { slug: "wordpress-developer", name: "WordPress Developer", category: "Engineering",
    skills: ["WordPress", "PHP", "Theme development", "Plugin development", "WooCommerce", "Site performance", "On-page SEO basics"],
    tools: ["WordPress", "PHP", "Elementor", "WooCommerce", "MySQL", "Yoast SEO"],
    blurb: "Builds and customises WordPress sites, themes, and plugins." },
  { slug: "salesforce-developer", name: "Salesforce Developer", category: "Engineering",
    skills: ["Apex", "Lightning Web Components", "SOQL", "Salesforce data model", "Flow automation", "Integration APIs"],
    tools: ["Salesforce", "Apex", "Lightning Web Components", "Visualforce", "Salesforce DX", "Workbench"],
    blurb: "Customises and extends the Salesforce platform with code and config." },
  { slug: "sap-abap-consultant", name: "SAP ABAP Consultant", category: "Engineering",
    skills: ["ABAP", "Data Dictionary", "ALV reports", "BAPI and BADI", "Smart Forms", "Performance tuning", "Debugging"],
    tools: ["SAP ABAP", "SAP HANA", "SAP Fiori", "Eclipse ADT", "SQL"],
    blurb: "Develops and maintains custom SAP functionality in ABAP." },
  { slug: "servicenow-developer", name: "ServiceNow Developer", category: "Engineering",
    skills: ["ServiceNow scripting", "ITSM workflows", "Business rules", "Client scripts", "Service Catalog", "Integrations"],
    tools: ["ServiceNow", "JavaScript", "Flow Designer", "IntegrationHub", "REST APIs"],
    blurb: "Configures and extends the ServiceNow platform for IT service management." },
  { slug: "rpa-developer", name: "RPA Developer", category: "Engineering",
    skills: ["Process automation", "Workflow design", "Exception handling", "Bot deployment", "Process documentation", "Orchestrator management"],
    tools: ["UiPath", "Automation Anywhere", "Blue Prism", "Power Automate", "Python"],
    blurb: "Automates repetitive business processes with software robots." },
  { slug: "embedded-systems-engineer", name: "Embedded Systems Engineer", category: "Engineering",
    skills: ["Embedded C", "Microcontrollers", "RTOS", "I2C / SPI / UART protocols", "Interrupt handling", "Hardware debugging"],
    tools: ["Embedded C", "ARM Cortex", "FreeRTOS", "Keil uVision", "MATLAB", "Oscilloscope"],
    blurb: "Writes software that runs directly on microcontrollers and devices." },
  { slug: "site-reliability-engineer", name: "Site Reliability Engineer", category: "Engineering",
    skills: ["SLOs and error budgets", "Observability", "Incident response", "Capacity planning", "Automation", "Postmortem analysis"],
    tools: ["Kubernetes", "Prometheus", "Grafana", "Terraform", "PagerDuty"],
    blurb: "Keeps production systems reliable through automation and measurement." },
  { slug: "solution-architect", name: "Solution Architect", category: "Engineering",
    skills: ["Solution design", "Integration architecture", "Non-functional requirements", "Cloud migration", "Cost modelling", "Stakeholder presentations"],
    tools: ["AWS", "Azure", "Kubernetes", "Terraform", "draw.io"],
    blurb: "Designs end-to-end technical solutions against business requirements." },
  { slug: "technical-lead", name: "Technical Lead", category: "Engineering",
    skills: ["Technical design", "Code review", "Mentoring", "Sprint planning", "Estimation", "Production debugging"],
    tools: ["Git", "JIRA", "Docker", "Jenkins", "Confluence"],
    blurb: "Leads a development team's technical direction and delivery." },
  { slug: "database-administrator", name: "Database Administrator", category: "Engineering",
    skills: ["Query tuning", "Backup and recovery", "Replication", "Indexing strategy", "High availability", "Access control"],
    tools: ["Oracle", "PostgreSQL", "MySQL", "SQL Server", "MongoDB"],
    blurb: "Keeps databases fast, available, and recoverable." },
  { slug: "system-administrator", name: "System Administrator", category: "Engineering",
    skills: ["Linux administration", "Shell scripting", "User and access management", "Patch management", "Backup and restore", "Monitoring"],
    tools: ["Linux", "Bash", "Ansible", "Active Directory", "Nagios"],
    blurb: "Maintains servers, operating systems, and internal infrastructure." },
  { slug: "network-engineer", name: "Network Engineer", category: "Engineering",
    skills: ["Routing and switching", "TCP/IP", "Subnetting", "VLANs", "Firewalls", "VPN", "Network troubleshooting"],
    tools: ["Cisco IOS", "Wireshark", "Packet Tracer", "Fortinet", "SolarWinds"],
    blurb: "Designs, configures, and troubleshoots enterprise networks." },
  { slug: "security-engineer", name: "Security Engineer", category: "Engineering",
    skills: ["Application security", "Threat modelling", "Penetration testing", "Identity and access management", "Encryption", "Secure code review"],
    tools: ["Burp Suite", "OWASP ZAP", "Nessus", "HashiCorp Vault", "Splunk"],
    blurb: "Builds and hardens the security controls protecting software systems." },
  { slug: "automation-test-engineer", name: "Automation Test Engineer", category: "Engineering",
    skills: ["Test automation frameworks", "Page Object Model", "API testing", "CI integration", "Cross-browser testing", "Defect analysis"],
    tools: ["Selenium", "Playwright", "TestNG", "Postman", "Jenkins"],
    blurb: "Writes automated test suites that catch regressions before release." },
  { slug: "ai-engineer", name: "AI Engineer", category: "Engineering",
    skills: ["LLM integration", "Prompt engineering", "RAG pipelines", "Vector search", "Model evaluation", "API orchestration"],
    tools: ["Python", "LangChain", "OpenAI API", "Hugging Face", "FastAPI", "Pinecone"],
    blurb: "Builds applications on top of large language and foundation models." },
  { slug: "mainframe-developer", name: "Mainframe Developer", category: "Engineering",
    skills: ["COBOL", "JCL", "VSAM", "DB2", "CICS", "Batch processing", "Production support"],
    tools: ["COBOL", "JCL", "DB2", "CICS", "TSO/ISPF", "Endevor"],
    blurb: "Maintains and enhances core banking and insurance mainframe systems." },

  // ── Data & Analytics (expansion) ──────────────────────────────────────────
  { slug: "mlops-engineer", name: "MLOps Engineer", category: "Data & Analytics",
    skills: ["Model deployment", "CI/CD for ML", "Model monitoring", "Feature stores", "Experiment tracking", "Containerisation"],
    tools: ["MLflow", "Kubeflow", "Docker", "Kubernetes", "Airflow", "AWS SageMaker"],
    blurb: "Operates the pipelines that train, ship, and monitor ML models." },
  { slug: "etl-developer", name: "ETL Developer", category: "Data & Analytics",
    skills: ["ETL design", "Data mapping", "Incremental loads", "SQL tuning", "Data quality checks", "Job scheduling"],
    tools: ["Informatica", "Talend", "SSIS", "SQL", "Airflow"],
    blurb: "Builds the extract-transform-load jobs that feed data warehouses." },
  { slug: "bi-developer", name: "BI Developer", category: "Data & Analytics",
    skills: ["Data modelling", "DAX", "Dashboard design", "SQL", "Report automation", "Requirements gathering"],
    tools: ["Power BI", "Tableau", "SQL Server", "DAX", "Excel"],
    blurb: "Builds the dashboards and reports a business runs on." },
  { slug: "analytics-engineer", name: "Analytics Engineer", category: "Data & Analytics",
    skills: ["Dimensional modelling", "SQL", "Data testing", "Metric definitions", "Documentation", "Version control"],
    tools: ["dbt", "Snowflake", "BigQuery", "Looker", "Git"],
    blurb: "Turns raw warehouse tables into trusted, documented data models." },
  { slug: "nlp-engineer", name: "NLP Engineer", category: "Data & Analytics",
    skills: ["Tokenisation", "Transformers", "Text classification", "Named entity recognition", "Embeddings", "Model fine-tuning"],
    tools: ["Python", "Hugging Face", "spaCy", "PyTorch", "NLTK"],
    blurb: "Builds models that understand and generate human language." },
  { slug: "computer-vision-engineer", name: "Computer Vision Engineer", category: "Data & Analytics",
    skills: ["Image preprocessing", "CNN architectures", "Object detection", "Image segmentation", "Model optimisation", "Data annotation"],
    tools: ["Python", "OpenCV", "PyTorch", "TensorFlow", "YOLO"],
    blurb: "Builds models that interpret images and video." },
  { slug: "data-architect", name: "Data Architect", category: "Data & Analytics",
    skills: ["Data modelling", "Warehouse architecture", "Data governance", "Master data management", "Access design", "Migration planning"],
    tools: ["Snowflake", "Databricks", "SQL", "ERwin", "AWS"],
    blurb: "Designs how data is stored, governed, and moved across an organisation." },
  { slug: "big-data-engineer", name: "Big Data Engineer", category: "Data & Analytics",
    skills: ["Distributed processing", "Spark SQL", "Partitioning", "Cluster tuning", "Streaming ingestion", "Data lake design"],
    tools: ["Spark", "Hadoop", "Hive", "Kafka", "Databricks"],
    blurb: "Processes data at petabyte scale on distributed clusters." },
  { slug: "quantitative-analyst", name: "Quantitative Analyst", category: "Data & Analytics",
    skills: ["Statistical modelling", "Time series analysis", "Derivatives pricing", "Risk metrics", "Backtesting", "Python programming"],
    tools: ["Python", "R", "MATLAB", "SQL", "NumPy", "Excel"],
    blurb: "Builds quantitative models for trading, pricing, and risk." },
  { slug: "sql-developer", name: "SQL Developer", category: "Data & Analytics",
    skills: ["SQL", "Stored procedures", "Query optimisation", "Indexing", "Data modelling", "Triggers and views"],
    tools: ["SQL Server", "PostgreSQL", "MySQL", "Oracle", "SSMS"],
    blurb: "Writes and tunes the SQL that powers reporting and applications." },

  // ── Product & Design (expansion) ──────────────────────────────────────────
  { slug: "associate-product-manager", name: "Associate Product Manager", category: "Product & Design",
    skills: ["User research", "Requirement writing", "Backlog grooming", "Metrics analysis", "Wireframing", "Competitor analysis"],
    tools: ["JIRA", "Figma", "Google Analytics", "Notion", "SQL"],
    blurb: "Entry-level product role owning features under a senior PM." },
  { slug: "technical-program-manager", name: "Technical Program Manager", category: "Product & Design",
    skills: ["Cross-team planning", "Dependency management", "Risk tracking", "Release management", "Technical judgement", "Stakeholder reporting"],
    tools: ["JIRA", "Confluence", "Smartsheet", "Excel", "Slack"],
    blurb: "Drives large technical programmes across multiple engineering teams." },
  { slug: "scrum-master", name: "Scrum Master", category: "Product & Design",
    skills: ["Scrum ceremonies", "Backlog refinement", "Impediment removal", "Agile coaching", "Velocity tracking", "Retrospectives"],
    tools: ["JIRA", "Confluence", "Azure DevOps", "Miro"],
    blurb: "Facilitates agile delivery and removes blockers for the team." },
  { slug: "ux-researcher", name: "UX Researcher", category: "Product & Design",
    skills: ["User interviews", "Usability testing", "Survey design", "Persona development", "Journey mapping", "Qualitative analysis"],
    tools: ["Figma", "Maze", "Dovetail", "Hotjar", "Miro"],
    blurb: "Uncovers what users actually need through structured research." },
  { slug: "video-editor", name: "Video Editor", category: "Product & Design",
    skills: ["Video editing", "Colour grading", "Sound design", "Storyboarding", "Subtitling", "Export optimisation"],
    tools: ["Premiere Pro", "After Effects", "DaVinci Resolve", "Final Cut Pro", "Audition"],
    blurb: "Cuts and finishes video content for brands and creators." },
  { slug: "interior-designer", name: "Interior Designer", category: "Product & Design",
    skills: ["Space planning", "3D visualisation", "Material selection", "Lighting design", "Client presentations", "BOQ and costing"],
    tools: ["AutoCAD", "SketchUp", "3ds Max", "Revit", "V-Ray"],
    blurb: "Designs functional, finished interior spaces for homes and offices." },

  // ── Marketing (expansion) ─────────────────────────────────────────────────
  { slug: "social-media-manager", name: "Social Media Manager", category: "Marketing",
    skills: ["Content calendar planning", "Community management", "Copywriting", "Paid social", "Analytics reporting", "Creator coordination"],
    tools: ["Meta Business Suite", "Hootsuite", "Buffer", "Canva", "Instagram Insights"],
    blurb: "Owns a brand's presence and growth across social platforms." },
  { slug: "performance-marketing-manager", name: "Performance Marketing Manager", category: "Marketing",
    skills: ["Paid acquisition", "Bid strategy", "ROAS optimisation", "Audience targeting", "Landing page testing", "Attribution"],
    tools: ["Google Ads", "Meta Ads", "GA4", "Google Tag Manager", "AppsFlyer"],
    blurb: "Runs paid channels against a measurable cost-per-acquisition target." },
  { slug: "brand-manager", name: "Brand Manager", category: "Marketing",
    skills: ["Brand positioning", "Campaign planning", "Market research", "Media planning", "Budget management", "Packaging and identity"],
    tools: ["Google Analytics", "Nielsen", "Excel", "Canva", "Adobe Creative Suite"],
    blurb: "Owns how a brand is positioned, seen, and remembered." },
  { slug: "content-marketing-manager", name: "Content Marketing Manager", category: "Marketing",
    skills: ["Content strategy", "Editorial calendar", "SEO", "Distribution", "Lead nurturing", "Performance analysis"],
    tools: ["WordPress", "HubSpot", "Ahrefs", "GA4", "Notion"],
    blurb: "Plans and runs the content engine that brings in organic demand." },
  { slug: "email-marketing-specialist", name: "Email Marketing Specialist", category: "Marketing",
    skills: ["Campaign design", "List segmentation", "A/B testing", "Deliverability", "Automation flows", "Copywriting"],
    tools: ["Mailchimp", "Klaviyo", "HubSpot", "Braze", "Litmus"],
    blurb: "Designs and sends email campaigns and lifecycle automations." },
  { slug: "growth-marketer", name: "Growth Marketer", category: "Marketing",
    skills: ["Funnel analysis", "Experimentation", "Retention loops", "Referral programmes", "Cohort analysis", "Paid and organic mix"],
    tools: ["Mixpanel", "Amplitude", "Google Ads", "SQL", "Optimizely"],
    blurb: "Runs experiments across the funnel to compound acquisition and retention." },
  { slug: "copywriter", name: "Copywriter", category: "Marketing",
    skills: ["Copywriting", "Brand voice", "Ad copy", "Headline testing", "Audience research", "Editing"],
    tools: ["Google Docs", "Grammarly", "Notion", "Canva", "Figma"],
    blurb: "Writes the words that sell a product or carry a campaign." },
  { slug: "technical-writer", name: "Technical Writer", category: "Marketing",
    skills: ["Technical documentation", "API documentation", "Information architecture", "Style guides", "Editing", "Diagramming"],
    tools: ["Markdown", "Confluence", "Git", "MadCap Flare", "Snagit"],
    blurb: "Turns complex products into documentation people can follow." },
  { slug: "product-marketing-manager", name: "Product Marketing Manager", category: "Marketing",
    skills: ["Positioning and messaging", "Go-to-market planning", "Competitive analysis", "Sales enablement", "Launch management", "Customer research"],
    tools: ["HubSpot", "Notion", "Figma", "Amplitude", "Excel"],
    blurb: "Owns how a product is positioned, launched, and sold." },

  // ── Sales & Customer (expansion) ──────────────────────────────────────────
  { slug: "business-development-executive", name: "Business Development Executive", category: "Sales & Customer",
    skills: ["Lead generation", "Cold calling", "Market mapping", "Proposal writing", "CRM hygiene", "Negotiation"],
    tools: ["LinkedIn Sales Navigator", "HubSpot", "Zoho CRM", "Excel", "Lusha"],
    blurb: "Opens new business conversations and builds early pipeline." },
  { slug: "business-development-manager", name: "Business Development Manager", category: "Sales & Customer",
    skills: ["Partnership development", "Revenue planning", "Pricing negotiation", "Market expansion", "Team management", "Forecasting"],
    tools: ["Salesforce", "HubSpot", "LinkedIn Sales Navigator", "Power BI", "Excel"],
    blurb: "Owns new-market and partnership revenue for a region or segment." },
  { slug: "inside-sales-representative", name: "Inside Sales Representative", category: "Sales & Customer",
    skills: ["Outbound prospecting", "Discovery calls", "Objection handling", "Email sequencing", "Pipeline hygiene", "Quota attainment"],
    tools: ["Salesforce", "Outreach", "HubSpot", "ZoomInfo", "Gong"],
    blurb: "Sells remotely by phone and email against a monthly quota." },
  { slug: "pre-sales-consultant", name: "Pre-Sales Consultant", category: "Sales & Customer",
    skills: ["Solution demos", "RFP response", "Technical discovery", "Proof of concept", "Proposal design", "Stakeholder presentations"],
    tools: ["Salesforce", "PowerPoint", "Confluence", "Postman", "Excel"],
    blurb: "Provides the technical credibility that closes enterprise deals." },
  { slug: "sales-manager", name: "Sales Manager", category: "Sales & Customer",
    skills: ["Team management", "Territory planning", "Forecasting", "Sales coaching", "Pipeline review", "Incentive design"],
    tools: ["Salesforce", "HubSpot", "Power BI", "Zoho CRM", "Excel"],
    blurb: "Leads a sales team to hit revenue targets." },
  { slug: "relationship-manager", name: "Relationship Manager", category: "Sales & Customer",
    skills: ["Portfolio management", "Cross-selling", "KYC and compliance", "Client servicing", "Financial product knowledge", "Target achievement"],
    tools: ["Finacle", "CRMNext", "Salesforce", "Excel", "MS Office"],
    blurb: "Manages a book of banking or insurance clients and grows their value." },
  { slug: "customer-support-executive", name: "Customer Support Executive", category: "Sales & Customer",
    skills: ["Ticket handling", "Product knowledge", "De-escalation", "SLA adherence", "Written communication", "CSAT improvement"],
    tools: ["Zendesk", "Freshdesk", "Intercom", "Salesforce Service Cloud", "Slack"],
    blurb: "Resolves customer issues over chat, email, and phone." },
  { slug: "retail-store-manager", name: "Retail Store Manager", category: "Sales & Customer",
    skills: ["Store operations", "Inventory management", "Sales target management", "Staff scheduling", "Visual merchandising", "Shrinkage control"],
    tools: ["POS systems", "SAP Retail", "Excel", "Power BI", "Tally"],
    blurb: "Runs a retail outlet's sales, stock, staff, and standards." },

  // ── Business & Operations (expansion) ─────────────────────────────────────
  { slug: "chartered-accountant", name: "Chartered Accountant", category: "Business & Operations",
    skills: ["Statutory audit", "Financial reporting", "Direct and indirect tax", "Ind AS", "Internal controls", "GST compliance"],
    tools: ["Tally", "SAP FICO", "Excel", "ClearTax", "Zoho Books"],
    blurb: "Signs off on accounts, audits, and tax positions for a business." },
  { slug: "investment-banking-analyst", name: "Investment Banking Analyst", category: "Business & Operations",
    skills: ["Financial modelling", "DCF and comparables valuation", "Pitch book preparation", "Due diligence", "Market research", "Excel modelling"],
    tools: ["Excel", "PowerPoint", "Bloomberg", "Capital IQ", "FactSet"],
    blurb: "Builds the models and materials behind M&A and capital-raising deals." },
  { slug: "credit-analyst", name: "Credit Analyst", category: "Business & Operations",
    skills: ["Credit appraisal", "Financial statement analysis", "Ratio analysis", "Risk rating", "Loan documentation", "Industry research"],
    tools: ["Excel", "SQL", "Power BI", "CIBIL", "Moody's Analytics"],
    blurb: "Assesses whether a borrower can and will repay." },
  { slug: "internal-auditor", name: "Internal Auditor", category: "Business & Operations",
    skills: ["Risk assessment", "Audit planning", "Internal controls testing", "Process walkthroughs", "Audit reporting", "SOX compliance"],
    tools: ["Excel", "SAP", "ACL Analytics", "TeamMate", "Power BI"],
    blurb: "Tests whether a company's controls and processes actually work." },
  { slug: "tax-consultant", name: "Tax Consultant", category: "Business & Operations",
    skills: ["Income tax", "GST", "Return filing", "Transfer pricing", "Tax assessments", "Advisory drafting"],
    tools: ["ClearTax", "Tally", "Winman", "Excel", "SAP"],
    blurb: "Advises on and files direct and indirect tax positions." },
  { slug: "payroll-executive", name: "Payroll Executive", category: "Business & Operations",
    skills: ["Payroll processing", "PF and ESI compliance", "TDS on salary", "Attendance reconciliation", "Full and final settlement", "Payslip generation"],
    tools: ["GreytHR", "Zoho Payroll", "Darwinbox", "SAP HR", "Excel"],
    blurb: "Runs accurate, compliant monthly payroll." },
  { slug: "hr-executive", name: "HR Executive", category: "Business & Operations",
    skills: ["Onboarding", "HR documentation", "Attendance and leave management", "Employee engagement", "Statutory compliance", "Exit formalities"],
    tools: ["GreytHR", "Darwinbox", "Zoho People", "Keka", "Excel"],
    blurb: "Handles day-to-day HR operations for employees." },
  { slug: "talent-acquisition-specialist", name: "Talent Acquisition Specialist", category: "Business & Operations",
    skills: ["Sourcing", "Boolean search", "Interview coordination", "Offer negotiation", "Pipeline reporting", "Employer branding"],
    tools: ["Naukri", "LinkedIn Recruiter", "Greenhouse", "Lever", "Excel"],
    blurb: "Owns hiring pipelines end to end for assigned roles." },
  { slug: "learning-and-development-manager", name: "Learning & Development Manager", category: "Business & Operations",
    skills: ["Training needs analysis", "Curriculum design", "Facilitation", "LMS administration", "Impact measurement", "Vendor management"],
    tools: ["Moodle", "Cornerstone", "Articulate 360", "Zoom", "Excel"],
    blurb: "Builds and runs the programmes that upskill an organisation." },
  { slug: "supply-chain-manager", name: "Supply Chain Manager", category: "Business & Operations",
    skills: ["Demand planning", "Inventory optimisation", "Supplier management", "Logistics coordination", "Sales and operations planning", "Cost reduction"],
    tools: ["SAP MM", "Oracle SCM", "Kinaxis", "Power BI", "Excel"],
    blurb: "Keeps supply, inventory, and demand in balance end to end." },
  { slug: "procurement-manager", name: "Procurement Manager", category: "Business & Operations",
    skills: ["Vendor sourcing", "RFQ and tendering", "Contract negotiation", "Cost savings", "Purchase order management", "Supplier audits"],
    tools: ["SAP MM", "SAP Ariba", "Coupa", "Power BI", "Excel"],
    blurb: "Buys what the business needs at the right price and terms." },
  { slug: "business-operations-analyst", name: "Business Operations Analyst", category: "Business & Operations",
    skills: ["Process mapping", "KPI reporting", "SQL", "Report automation", "Root cause analysis", "Stakeholder management"],
    tools: ["SQL", "Excel", "Power BI", "Tableau", "JIRA"],
    blurb: "Measures and improves how the business runs day to day." },
  { slug: "risk-analyst", name: "Risk Analyst", category: "Business & Operations",
    skills: ["Risk identification", "Scenario analysis", "Control testing", "Regulatory reporting", "Statistical modelling", "Risk register maintenance"],
    tools: ["Excel", "SQL", "SAS", "Archer", "Power BI"],
    blurb: "Quantifies and monitors the risks a business is carrying." },
  { slug: "banking-operations-executive", name: "Banking Operations Executive", category: "Business & Operations",
    skills: ["Account opening", "KYC verification", "Transaction processing", "Reconciliation", "Regulatory reporting", "Customer servicing"],
    tools: ["Finacle", "Flexcube", "SWIFT", "Oracle", "Excel"],
    blurb: "Processes and reconciles the back-office work behind banking products." },

  // ── Core Engineering (campus placement heavy) ─────────────────────────────
  { slug: "mechanical-engineer", name: "Mechanical Engineer", category: "Core Engineering",
    skills: ["Machine design", "Thermodynamics", "Strength of materials", "GD&T", "Manufacturing processes", "CAD modelling", "FEA basics"],
    tools: ["AutoCAD", "SolidWorks", "CATIA", "ANSYS", "Excel"],
    blurb: "Designs and validates mechanical components and systems." },
  { slug: "civil-engineer", name: "Civil Engineer", category: "Core Engineering",
    skills: ["Structural analysis", "RCC design", "Estimation and costing", "Surveying", "Construction planning", "Concrete technology", "Quality control"],
    tools: ["AutoCAD", "STAAD.Pro", "ETABS", "Revit", "MS Project"],
    blurb: "Designs and supervises buildings, roads, and infrastructure." },
  { slug: "electrical-engineer", name: "Electrical Engineer", category: "Core Engineering",
    skills: ["Power systems", "Electrical machines", "Circuit design", "Load calculation", "Panel design", "Protection and switchgear"],
    tools: ["AutoCAD Electrical", "ETAP", "MATLAB", "PLC", "Multisim"],
    blurb: "Designs and maintains electrical power and control systems." },
  { slug: "electronics-communication-engineer", name: "Electronics & Communication Engineer", category: "Core Engineering",
    skills: ["Digital electronics", "Analog circuits", "Signal processing", "Communication systems", "Microcontrollers", "PCB design"],
    tools: ["MATLAB", "Verilog", "Proteus", "Altium Designer", "Keil uVision"],
    blurb: "Designs electronic circuits and communication hardware." },
  { slug: "automobile-engineer", name: "Automobile Engineer", category: "Core Engineering",
    skills: ["Vehicle dynamics", "IC engines", "Powertrain systems", "CAD modelling", "Failure analysis", "Automotive standards"],
    tools: ["CATIA", "AutoCAD", "ANSYS", "MATLAB", "GT-Power"],
    blurb: "Designs, tests, and improves vehicles and their subsystems." },
  { slug: "chemical-engineer", name: "Chemical Engineer", category: "Core Engineering",
    skills: ["Process design", "Mass and energy balance", "Heat transfer", "Reaction engineering", "P&ID interpretation", "Process safety"],
    tools: ["Aspen Plus", "Aspen HYSYS", "AutoCAD", "MATLAB", "Excel"],
    blurb: "Designs and operates chemical and process plants." },
  { slug: "aerospace-engineer", name: "Aerospace Engineer", category: "Core Engineering",
    skills: ["Aerodynamics", "Propulsion", "Structural analysis", "Flight mechanics", "CFD basics", "Composite materials"],
    tools: ["ANSYS Fluent", "CATIA", "MATLAB", "NASTRAN", "XFLR5"],
    blurb: "Designs and analyses aircraft and spacecraft systems." },
  { slug: "production-engineer", name: "Production Engineer", category: "Core Engineering",
    skills: ["Production planning", "Lean manufacturing", "Line balancing", "OEE improvement", "Quality control", "Root cause analysis"],
    tools: ["SAP PP", "Minitab", "AutoCAD", "Power BI", "Excel"],
    blurb: "Runs and improves the manufacturing line's output and quality." },
  { slug: "industrial-engineer", name: "Industrial Engineer", category: "Core Engineering",
    skills: ["Time and motion study", "Process improvement", "Layout planning", "Six Sigma", "Capacity planning", "Cost reduction"],
    tools: ["Minitab", "AutoCAD", "SAP", "Arena Simulation", "Excel"],
    blurb: "Optimises how people, machines, and material flow through a plant." },
  { slug: "instrumentation-engineer", name: "Instrumentation Engineer", category: "Core Engineering",
    skills: ["Process instrumentation", "PLC and SCADA", "Control loop tuning", "Calibration", "P&ID interpretation", "Sensor selection"],
    tools: ["PLC", "SCADA", "DCS", "AutoCAD", "MATLAB"],
    blurb: "Specifies and maintains the instruments that measure and control a plant." },
  { slug: "structural-engineer", name: "Structural Engineer", category: "Core Engineering",
    skills: ["Structural analysis", "RCC and steel design", "Load calculations", "Seismic design", "Detailing", "IS code compliance"],
    tools: ["STAAD.Pro", "ETABS", "SAFE", "AutoCAD", "Revit"],
    blurb: "Designs the load-bearing structure of buildings and bridges." },
  { slug: "site-engineer", name: "Site Engineer", category: "Core Engineering",
    skills: ["Site supervision", "Quantity estimation", "Bar bending schedule", "Quality checks", "Safety compliance", "Progress reporting"],
    tools: ["AutoCAD", "MS Project", "Primavera", "Total Station", "Excel"],
    blurb: "Runs day-to-day execution and quality on a construction site." },
  { slug: "quantity-surveyor", name: "Quantity Surveyor", category: "Core Engineering",
    skills: ["Quantity take-off", "BOQ preparation", "Rate analysis", "Tender documentation", "Cost control", "Variation claims"],
    tools: ["Excel", "AutoCAD", "Revit", "Primavera", "CANDY"],
    blurb: "Measures and controls the cost of construction work." },
  { slug: "hvac-engineer", name: "HVAC Engineer", category: "Core Engineering",
    skills: ["Heat load calculation", "Duct design", "Chiller selection", "Ventilation design", "Psychrometrics", "Energy efficiency"],
    tools: ["Carrier HAP", "AutoCAD", "Revit MEP", "Duct Sizer", "Excel"],
    blurb: "Designs heating, ventilation, and air-conditioning systems." },
  { slug: "maintenance-engineer", name: "Maintenance Engineer", category: "Core Engineering",
    skills: ["Preventive maintenance", "Breakdown analysis", "Spare parts planning", "Root cause analysis", "Condition monitoring", "Safety procedures"],
    tools: ["SAP PM", "CMMS", "Vibration analyser", "Power BI", "Excel"],
    blurb: "Keeps plant and equipment running with minimum downtime." },
  { slug: "quality-control-engineer", name: "Quality Control Engineer", category: "Core Engineering",
    skills: ["Inspection and testing", "Statistical process control", "Root cause analysis", "ISO 9001", "Measurement instruments", "CAPA documentation"],
    tools: ["Minitab", "CMM", "SAP QM", "AutoCAD", "Excel"],
    blurb: "Verifies that manufactured output meets specification." },
  { slug: "cad-designer", name: "CAD Designer", category: "Core Engineering",
    skills: ["2D drafting", "3D modelling", "GD&T", "Sheet metal design", "Assembly drawings", "Revision control"],
    tools: ["AutoCAD", "SolidWorks", "CATIA", "Creo", "Autodesk Inventor"],
    blurb: "Produces the drawings and models engineering and manufacturing work from." },
  { slug: "architect", name: "Architect", category: "Core Engineering",
    skills: ["Architectural design", "Space planning", "Building codes", "Construction drawings", "3D visualisation", "Client presentations"],
    tools: ["AutoCAD", "Revit", "SketchUp", "Lumion", "Photoshop"],
    blurb: "Designs buildings from concept through construction documentation." },

  // ── Healthcare ────────────────────────────────────────────────────────────
  { slug: "staff-nurse", name: "Staff Nurse", category: "Healthcare",
    skills: ["Patient assessment", "Medication administration", "IV cannulation", "Wound care", "Vital signs monitoring", "Infection control", "Clinical documentation"],
    tools: ["Hospital EMR", "Infusion pump", "Glucometer", "ECG machine", "Ventilator"],
    blurb: "Delivers direct bedside patient care in a clinical setting." },
  { slug: "pharmacist", name: "Pharmacist", category: "Healthcare",
    skills: ["Dispensing", "Drug interaction checks", "Prescription verification", "Inventory management", "Patient counselling", "Pharmacovigilance"],
    tools: ["Pharmacy management software", "Micromedex", "Hospital EMR", "Excel", "Tally"],
    blurb: "Dispenses medicines safely and advises on their use." },
  { slug: "medical-laboratory-technician", name: "Medical Laboratory Technician", category: "Healthcare",
    skills: ["Sample collection", "Haematology testing", "Biochemistry assays", "Microbiology culture", "Quality control", "Lab safety"],
    tools: ["Autoanalyser", "Centrifuge", "Microscope", "LIS", "Excel"],
    blurb: "Runs the diagnostic tests clinicians base decisions on." },
  { slug: "physiotherapist", name: "Physiotherapist", category: "Healthcare",
    skills: ["Musculoskeletal assessment", "Exercise prescription", "Manual therapy", "Electrotherapy", "Gait training", "Patient education"],
    tools: ["TENS unit", "Ultrasound therapy machine", "Goniometer", "Hospital EMR", "Resistance bands"],
    blurb: "Restores movement and function through physical rehabilitation." },
  { slug: "radiology-technician", name: "Radiology Technician", category: "Healthcare",
    skills: ["X-ray positioning", "CT and MRI protocols", "Radiation safety", "Contrast administration", "Image quality checks", "Patient preparation"],
    tools: ["X-ray machine", "CT scanner", "MRI scanner", "PACS", "RIS"],
    blurb: "Acquires diagnostic images safely and accurately." },
  { slug: "clinical-research-associate", name: "Clinical Research Associate", category: "Healthcare",
    skills: ["Protocol compliance", "Site monitoring", "Informed consent process", "Good Clinical Practice", "Source data verification", "Query resolution"],
    tools: ["Medidata Rave", "Veeva Vault", "CTMS", "eTMF", "Excel"],
    blurb: "Monitors clinical trial sites for data quality and compliance." },
  { slug: "medical-coder", name: "Medical Coder", category: "Healthcare",
    skills: ["ICD-10 coding", "CPT coding", "HCPCS", "Medical terminology", "Chart abstraction", "Coding audits"],
    tools: ["ICD-10 codebook", "3M Encoder", "Epic", "Athenahealth", "Excel"],
    blurb: "Translates clinical documentation into billing codes." },
  { slug: "hospital-administrator", name: "Hospital Administrator", category: "Healthcare",
    skills: ["Operations management", "NABH accreditation", "Staff scheduling", "Budgeting", "Patient experience", "Vendor management"],
    tools: ["HIS", "Hospital EMR", "Power BI", "Tally", "Excel"],
    blurb: "Runs the non-clinical operations of a hospital or department." },
  { slug: "medical-representative", name: "Medical Representative", category: "Healthcare",
    skills: ["Product detailing", "Doctor relationship building", "Territory coverage", "Sales target achievement", "Pharmacology fundamentals", "Call reporting"],
    tools: ["Veeva CRM", "Excel", "MS PowerPoint", "Zoho CRM", "WhatsApp Business"],
    blurb: "Promotes pharmaceutical products to doctors and chemists in a territory." },

  // ── Education ─────────────────────────────────────────────────────────────
  { slug: "school-teacher", name: "School Teacher", category: "Education",
    skills: ["Lesson planning", "Classroom management", "Assessment design", "Differentiated instruction", "Parent communication", "Curriculum mapping"],
    tools: ["Google Classroom", "MS PowerPoint", "Excel", "Zoom", "Kahoot"],
    blurb: "Teaches a subject to school students and tracks their progress." },
  { slug: "lecturer", name: "Lecturer", category: "Education",
    skills: ["Subject expertise", "Lecture delivery", "Curriculum design", "Research and publication", "Student mentoring", "Evaluation and grading"],
    tools: ["MS PowerPoint", "Moodle", "Google Scholar", "LaTeX", "Zoom"],
    blurb: "Teaches and examines students at college or university level." },
  { slug: "academic-counsellor", name: "Academic Counsellor", category: "Education",
    skills: ["Student counselling", "Course advising", "Admission processes", "Follow-up and conversion", "Record keeping", "Parent interaction"],
    tools: ["Zoho CRM", "Excel", "Google Workspace", "Zoom", "LeadSquared"],
    blurb: "Guides students on course choices and shepherds them through admission." },
  { slug: "instructional-designer", name: "Instructional Designer", category: "Education",
    skills: ["Learning objectives", "Storyboarding", "Assessment design", "ADDIE model", "SCORM packaging", "Multimedia scripting"],
    tools: ["Articulate Storyline", "Camtasia", "Moodle", "Figma", "Canva"],
    blurb: "Designs structured learning experiences and e-learning content." },
  { slug: "corporate-trainer", name: "Corporate Trainer", category: "Education",
    skills: ["Training delivery", "Needs analysis", "Facilitation", "Role-play design", "Assessment and feedback", "Content development"],
    tools: ["MS PowerPoint", "Zoom", "Moodle", "Mentimeter", "Excel"],
    blurb: "Trains working professionals on skills, process, and product." },

  // ── Government & Public Sector ────────────────────────────────────────────
  { slug: "bank-probationary-officer", name: "Bank Probationary Officer", category: "Government & Public Sector",
    skills: ["Banking operations", "Credit fundamentals", "KYC and AML", "Customer relationship management", "Quantitative aptitude", "General awareness"],
    tools: ["Finacle", "Flexcube", "CRMNext", "Excel", "MS Office"],
    blurb: "Entry-level officer cadre role rotating across bank functions." },
  { slug: "bank-clerk", name: "Bank Clerk", category: "Government & Public Sector",
    skills: ["Cash handling", "Account maintenance", "Cheque clearing", "Customer servicing", "Data entry accuracy", "Daily reconciliation"],
    tools: ["Finacle", "Flexcube", "Excel", "MS Office", "Cash counting machine"],
    blurb: "Handles branch counter transactions and customer records." },
  { slug: "public-sector-graduate-engineer-trainee", name: "Graduate Engineer Trainee (PSU)", category: "Government & Public Sector",
    skills: ["Engineering fundamentals", "Technical drawing", "Plant operations", "Safety standards", "Report writing", "Project support"],
    tools: ["AutoCAD", "SAP", "MATLAB", "MS Project", "Excel"],
    blurb: "Structured graduate entry role in a public sector undertaking." },
  { slug: "government-junior-engineer", name: "Junior Engineer (Government)", category: "Government & Public Sector",
    skills: ["Estimation and costing", "Site supervision", "Tender documentation", "IS code compliance", "Measurement book entries", "Quality inspection"],
    tools: ["AutoCAD", "STAAD.Pro", "MS Project", "Total Station", "Excel"],
    blurb: "Supervises public works execution, measurement, and billing." },

  // ── Support & IT Operations ───────────────────────────────────────────────
  { slug: "technical-support-engineer", name: "Technical Support Engineer", category: "Support & IT Operations",
    skills: ["Troubleshooting", "Log analysis", "SQL querying", "Escalation management", "Customer communication", "Knowledge base authoring"],
    tools: ["Zendesk", "Jira Service Management", "SQL", "Postman", "Splunk"],
    blurb: "Diagnoses and resolves technical product issues for customers." },
  { slug: "it-support-specialist", name: "IT Support Specialist", category: "Support & IT Operations",
    skills: ["Hardware troubleshooting", "OS installation", "Software deployment", "Ticket management", "Remote support", "Asset management"],
    tools: ["Windows", "Active Directory", "ServiceNow", "TeamViewer", "Microsoft Intune"],
    blurb: "Keeps internal users' devices, accounts, and software working." },
  { slug: "desktop-support-engineer", name: "Desktop Support Engineer", category: "Support & IT Operations",
    skills: ["Desktop troubleshooting", "Peripheral and printer support", "OS imaging", "Antivirus management", "User onboarding", "Ticket documentation"],
    tools: ["Windows", "Active Directory", "SCCM", "AnyDesk", "ServiceNow"],
    blurb: "Provides hands-on support for end-user desktops and laptops." },
  { slug: "noc-engineer", name: "NOC Engineer", category: "Support & IT Operations",
    skills: ["Network monitoring", "Incident triage", "Escalation procedures", "Link troubleshooting", "Ticketing", "Shift handover reporting"],
    tools: ["SolarWinds", "Nagios", "Zabbix", "Wireshark", "ServiceNow"],
    blurb: "Monitors network and infrastructure health around the clock." },
  { slug: "service-desk-analyst", name: "Service Desk Analyst", category: "Support & IT Operations",
    skills: ["ITIL incident management", "Call logging", "SLA tracking", "First-call resolution", "Knowledge base usage", "Customer communication"],
    tools: ["ServiceNow", "Jira Service Management", "Freshservice", "Active Directory", "Excel"],
    blurb: "First point of contact for IT incidents and service requests." },

  // ── Legal & Compliance ────────────────────────────────────────────────────
  { slug: "legal-associate", name: "Legal Associate", category: "Legal & Compliance",
    skills: ["Legal research", "Drafting and vetting agreements", "Litigation support", "Due diligence", "Regulatory compliance", "Client advisory"],
    tools: ["SCC Online", "Manupatra", "MS Word", "DocuSign", "Excel"],
    blurb: "Researches, drafts, and advises on legal matters for clients." },
  { slug: "company-secretary", name: "Company Secretary", category: "Legal & Compliance",
    skills: ["Corporate governance", "Companies Act compliance", "Board meeting management", "ROC filings", "SEBI regulations", "Statutory registers"],
    tools: ["MCA portal", "MS Word", "Excel", "DocuSign", "SAP"],
    blurb: "Keeps a company compliant with corporate law and governance rules." },
  { slug: "compliance-officer", name: "Compliance Officer", category: "Legal & Compliance",
    skills: ["Regulatory mapping", "Policy drafting", "AML and KYC", "Audit coordination", "Training and awareness", "Incident reporting"],
    tools: ["Excel", "Archer", "Power BI", "MS Word", "SharePoint"],
    blurb: "Ensures the organisation meets its regulatory obligations." },
];

export function getSeoRole(slug: string): SeoRole | undefined {
  return SEO_ROLES.find((r) => r.slug === slug);
}

export function roleCategories(): string[] {
  return Array.from(new Set(SEO_ROLES.map((r) => r.category)));
}
