// Domain catalog: each domain is a hand-authored roadmap of topics.
// The lesson CONTENT for each topic is generated by AI on demand, so adding a
// domain or topic is just data — no per-topic authoring needed.

export interface DomainTopic {
  slug: string;
  title: string;
  blurb: string;
}

export interface Domain {
  slug: string;
  name: string;
  emoji: string;
  blurb: string;
  gradient: string;
  free: boolean; // whole domain free vs Pro
  roadmap: DomainTopic[];
}

/** Number of topics in each domain that are free for the free tier. */
export const FREE_TOPICS_PER_DOMAIN = 3;

const T = (slug: string, title: string, blurb: string): DomainTopic => ({ slug, title, blurb });

export const DOMAINS: Domain[] = [
  {
    slug: "data-engineering",
    name: "Data Engineering",
    emoji: "🛠️",
    blurb: "Build the pipelines that move and shape data at scale.",
    gradient: "from-sky-500 to-indigo-600",
    free: true,
    roadmap: [
      T("what-is-data-engineering", "What is Data Engineering?", "The role, the stack, and why it matters."),
      T("databases-and-sql", "Databases & SQL", "Relational tables, keys, and querying with SQL."),
      T("data-modeling", "Data Modeling", "Star schemas, normalization, and fact/dimension tables."),
      T("etl-vs-elt", "ETL vs ELT", "Extract, transform, load — and when to flip the order."),
      T("batch-processing-spark", "Batch Processing with Spark", "Distributed compute over huge datasets."),
      T("streaming-kafka", "Streaming with Kafka", "Real-time event pipelines and topics."),
      T("data-warehouses", "Data Warehouses", "Columnar stores like Snowflake & BigQuery."),
      T("data-lakes-lakehouse", "Data Lakes & Lakehouse", "Cheap raw storage and the lakehouse pattern."),
      T("orchestration-airflow", "Orchestration with Airflow", "Scheduling and DAGs for reliable pipelines."),
      T("data-quality-testing", "Data Quality & Testing", "Validation, contracts, and trustworthy data."),
      T("cloud-data-platforms", "Cloud Data Platforms", "AWS/GCP/Azure building blocks."),
      T("dataops-monitoring", "DataOps & Monitoring", "Observability, lineage, and on-call for data."),
    ],
  },
  {
    slug: "web-development",
    name: "Web Development",
    emoji: "🌐",
    blurb: "Go from HTML to full-stack apps you can ship.",
    gradient: "from-emerald-500 to-teal-600",
    free: true,
    roadmap: [
      T("how-the-web-works", "How the Web Works", "Browsers, servers, HTTP requests & responses."),
      T("html-css", "HTML & CSS", "Structure and style the page."),
      T("javascript", "JavaScript", "Make pages interactive."),
      T("dom-and-events", "The DOM & Events", "Manipulate the page and respond to clicks."),
      T("react-basics", "React Basics", "Components, props, and state."),
      T("apis-and-fetch", "APIs & Fetch", "Talk to servers and handle JSON."),
      T("backend-and-node", "Backend & Node", "Servers, routes, and middleware."),
      T("databases-web", "Databases", "Store and query app data."),
      T("auth", "Authentication", "Logins, sessions, and tokens."),
      T("deployment", "Deployment", "Ship your app to the world."),
    ],
  },
  {
    slug: "machine-learning",
    name: "Machine Learning",
    emoji: "🤖",
    blurb: "Teach computers to learn from data.",
    gradient: "from-fuchsia-500 to-purple-600",
    free: false,
    roadmap: [
      T("what-is-ml", "What is Machine Learning?", "Learning patterns instead of hard-coding rules."),
      T("math-for-ml", "Math for ML", "Vectors, gradients, and probability — gently."),
      T("data-preparation", "Data Preparation", "Cleaning, features, train/test splits."),
      T("supervised-learning", "Supervised Learning", "Regression & classification."),
      T("model-evaluation", "Model Evaluation", "Accuracy, precision/recall, overfitting."),
      T("unsupervised-learning", "Unsupervised Learning", "Clustering and dimensionality reduction."),
      T("neural-networks", "Neural Networks", "Layers, weights, and backprop."),
      T("deep-learning", "Deep Learning", "CNNs, RNNs, and transformers."),
      T("ml-deployment", "Deploying Models", "Serving predictions in production."),
    ],
  },
  {
    slug: "cloud-devops",
    name: "Cloud & DevOps",
    emoji: "☁️",
    blurb: "Automate, containerize, and run software reliably.",
    gradient: "from-amber-500 to-orange-600",
    free: false,
    roadmap: [
      T("linux-basics", "Linux Basics", "The shell, files, and permissions."),
      T("git-version-control", "Git & Version Control", "Branches, commits, and collaboration."),
      T("containers-docker", "Containers with Docker", "Package apps to run anywhere."),
      T("ci-cd", "CI/CD Pipelines", "Automated build, test, and deploy."),
      T("kubernetes", "Kubernetes", "Orchestrate containers at scale."),
      T("infrastructure-as-code", "Infrastructure as Code", "Terraform and reproducible infra."),
      T("cloud-fundamentals", "Cloud Fundamentals", "Compute, storage, and networking."),
      T("monitoring-observability", "Monitoring & Observability", "Metrics, logs, and alerts."),
    ],
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    emoji: "🛡️",
    blurb: "Understand and defend against digital threats.",
    gradient: "from-rose-500 to-red-600",
    free: false,
    roadmap: [
      T("security-fundamentals", "Security Fundamentals", "CIA triad, threats, and risk."),
      T("networking-security", "Networking Security", "Ports, firewalls, and protocols."),
      T("cryptography", "Cryptography", "Encryption, hashing, and keys."),
      T("web-security", "Web Security", "OWASP Top 10 and common attacks."),
      T("authentication-access", "Authentication & Access", "MFA, least privilege, and IAM."),
      T("ethical-hacking", "Ethical Hacking", "Reconnaissance and penetration testing."),
      T("incident-response", "Incident Response", "Detect, contain, and recover."),
    ],
  },
  {
    slug: "data-science",
    name: "Data Science",
    emoji: "📊",
    blurb: "Turn raw data into insights and decisions.",
    gradient: "from-cyan-500 to-blue-600",
    free: false,
    roadmap: [
      T("intro-data-science", "Intro to Data Science", "The workflow from question to insight."),
      T("statistics-basics", "Statistics Basics", "Distributions, mean/variance, and tests."),
      T("python-for-data", "Python for Data", "NumPy and Pandas essentials."),
      T("data-cleaning", "Data Cleaning", "Missing values, outliers, and tidy data."),
      T("data-visualization", "Data Visualization", "Charts that actually communicate."),
      T("exploratory-analysis", "Exploratory Analysis", "Finding patterns and correlations."),
      T("ml-for-data-science", "ML for Data Science", "Predictive models in practice."),
      T("storytelling", "Data Storytelling", "Communicating results to humans."),
    ],
  },
];

export function getDomain(slug: string): Domain | undefined {
  return DOMAINS.find((d) => d.slug === slug);
}

export function getDomainTopic(domainSlug: string, topicSlug: string): { domain: Domain; topic: DomainTopic; index: number } | undefined {
  const domain = getDomain(domainSlug);
  if (!domain) return undefined;
  const index = domain.roadmap.findIndex((t) => t.slug === topicSlug);
  if (index < 0) return undefined;
  return { domain, topic: domain.roadmap[index], index };
}

/** A topic is unlocked if it's the first, or the previous topic is mastered. */
export function isTopicUnlocked(index: number, masteredSlugs: Set<string>, roadmap: DomainTopic[]): boolean {
  if (index <= 0) return true;
  return masteredSlugs.has(roadmap[index - 1].slug);
}

/** A topic is accessible by plan if it's among the first free topics, or the user is Pro. */
export function isTopicAccessible(index: number, domain: Domain, pro: boolean): boolean {
  if (pro) return true;
  if (domain.free) return index < FREE_TOPICS_PER_DOMAIN;
  return false;
}
